### ISSUE TITLE
Add option to remove the VS Code logo and help when no file is open

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#104]
**Is your feature request related to a problem? Please describe.**

When there is no file open in VS Code, the logo will appear with some keyboard shortcuts.

![image](https://user-images.githubusercontent.com/11861253/129514524-ed846963-0733-44ff-9f56-6fcb6d78bc56.png)

**Describe the solution you'd like**

An option to disable or enable this section.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Unthrottled** [comment]
That's a good idea. I wanted to remove it when I first was implementing it, but I didn't try hard enough. I'll try harder when I get the time. It's not like I can read the text (nor do I care).

**Comment by justalemon** [comment]
> It's not like I can read the text

Me neither. Is just that the UI would look cleaner due to no obstructions being present.
