### ISSUE TITLE
Automatically re-apply the last Sticker and Wallpaper when a version change is detected

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#105]
**Is your feature request related to a problem? Please describe.**

As we probably all know, VS Code updates cause the Sticker and Wallpaper to be lost when they are installed. I was wondering if there is a way to automatically re-apply the Sticker and Wallpaper after the VS Code Version is changed.

**Describe the solution you'd like**

The Doki Theme should keep track of the last used Sticker and Wallpaper alongside the last VS Code version used.

Once an update is detected (version is changed), The Doki Theme detects this and re-applies the Sticker and Wallpaper, showing a message like:

> Your Visual Studio Code installation has been updated. Please reload the current window to reload your Sticker and/or Wallpaper.
> [Reload Window]

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Unthrottled** [comment]
>  I was wondering if there is a way to automatically re-apply the Sticker and Wallpaper after the VS Code Version is changed.

Yeah, pretty sure this could be done. [You can get the version version.](https://github.com/doki-theme/doki-theme-vscode/blob/5ba0f9d3a07e19f1402b634213851d20e632cf7b/src/CheckSumService.ts#L8). Just need to check the saved version & installed assets (that probably needs to be saved to) on plugin activation and install if vscode version number changed. 

I've got some things I am working on, so this might be a bit before I can get to it. I do like the idea though.
