### ISSUE TITLE
"Restart VS Code" should be "Reload Window"

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#106]
**Describe the bug**

The text for applying Stickers and Wallpapers says that you should Restart VS Code. It should instead say Reload Window, as this is what the button does and the minimum required to make the Sticker/Wallpaper visible on the screen.

**To Reproduce**

1. Install a Sticker or Wallpaper
2. See the notifications to find the following message(s) for Stickers or Wallpapers respectively:

> [Character's] Sticker Installed! Please restart your VSCode
> [Restart VSCode]

> [Character's] Wallpaper Installed! Please restart your VSCode
> [Restart VSCode]

**Expected Behavior**

You get the following message for installing Stickers or Wallpapers respectively:

> [Character's] Sticker Installed! Please reload your current window.
> [Reload Window]

> [Character's] Wallpaper Installed! Please reload your current window.
> [Reload Window]

**Environment**

Version: 1.60.0-insider (user setup)
Commit: 9dd4f31a21d63deea5e1fc322cfc802413b31d95
Date: 2021-08-16T05:21:19.431Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Doki-Theme: 15.1.0

**Screenshots**

![image](https://user-images.githubusercontent.com/11861253/129727747-ed9f50d4-e38e-4515-aeea-7452ea972354.png)

**Comment by Unthrottled** [comment]
> It should instead say Reload Window

Yup, I agree to. Feel free to submit a PR if you want to fix it, should be pretty easy. If not, might be a before I get to this.
