### ISSUE TITLE
"Please wait, installing [Character's] Sticker/Wallpaper." notification is not discarded

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#107]
**Describe the bug**

When the Sticker/Wallpaper is installed, the old "Please wait" notification will still be there.

I know that is just a small thing but I feel is worth to be reported.

**To Reproduce**

1. Install a Sticker/Wallpaper
2. Check your notifications

**Expected Behavior**

The "Please wait, installing [Character's] Sticker/Wallpaper." notification is discarded once is correctly installed.

**Environment**

Version: 1.60.0-insider (user setup)
Commit: 9dd4f31a21d63deea5e1fc322cfc802413b31d95
Date: 2021-08-16T05:21:19.431Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Doki-Theme: 15.1.0

**Screenshots**

![image](https://user-images.githubusercontent.com/11861253/129728806-990d6532-27e3-4bfa-8a8d-b8e6e888c44f.png)

**Comment by Unthrottled** [comment]
I dunno if we have the ability to close notifications programmatically. 
I added the `please wait` because there might be a small wait as the content is downloaded for the first time. This way the user knows something is happening when they ran it.

Might be easier to show the `please wait` only if the asset is not available locally.

**Comment by justalemon** [comment]
> I dunno if we have the ability to close notifications programmatically.

Not a VS Code Extension Developer, but I have seen other Extensions discard existing notifications. I'm not sure how this works.

**Comment by Unthrottled** [comment]
Turns out there is a [Progress API](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#progress-api) finna use that.
