### ISSUE TITLE
Command not found ( VSCode )

### ISSUE THREAD

**Issue by BappyWasTaken** [doki-theme/doki-theme-vscode#111]
Whenever I run "Doki-Theme: Install kanna's second sticker", I get the error
```
Command 'Doki-Theme: Install Kanna's Secondary Sticker' resulted in an error (command 'doki-theme.theme.Kanna.secondary' not found)
```

1. Install the theme
2. Run "Doki-Theme: Install Kanna's Secondary Sticker"

**Expected Behavior**
Installs the theme

**Environment**
Version: 1.60.0-insider (Universal)
Commit: 44568e5947efa4811419e529e80fb14b7554cf61
Date: 2021-08-23T10:42:53.526Z (6 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.0.0
Doki: v15.3.0

![image](https://user-images.githubusercontent.com/82696125/131265052-f9cd978e-820c-47eb-8400-d84149d50659.png)

**Comment by Unthrottled** [comment]
:thinking: That's curious.

Have you tried completely closing and opening VSCode again?

If that does not work, can you un-install, restart vscode, install the plugin, restart, then try to install the sticker?

**Comment by BappyWasTaken** [comment]
So I was on the ssh running Debian 10, and closing that seemed to fix it

**Comment by BappyWasTaken** [comment]
Alright so I had to install it on my system, then open the VPS and it works fine now.
