### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by kotx** [doki-theme/doki-theme-vscode#113]
It would be useful to publish the theme extension to https://open-vsx.org/, so that things like [Gitpod](https://gitpod.io) or code-server can install it more easily. (The VSCode Marketplace does not allow non-Microsoft editors to use its extensions)

**Comment by Unthrottled** [comment]
https://open-vsx.org/extension/unthrottled/doki-theme 

Done, thanks for bringing this to my attention! :clap:
