### ISSUE TITLE
Unable to change permissions to install visual studio

### ISSUE THREAD

**Issue by stan1199** [doki-theme/doki-theme-vscode#115]
$ sudo chown -R $(whoami) /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual\ Studio\ Code.app/Contents/
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//Frameworks/Code Helper (Renderer).app: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//Frameworks: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//Info.plist: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//PkgInfo: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents/: Read-only file system

Looks like in the new catalina macOS, we can not change the permission as it is only a read-only file system. Any workaround for this?

**Comment by Unthrottled** [comment]
I haven't run into this issue on Catalina or Big Sur. How did you install your VSCode? Maybe you should try an installation method that puts it in a writable directory. This installation method might work: https://code.visualstudio.com/docs/setup/mac#_installation

**Comment by JustinTowers** [comment]
same, just got an m1 pro mac and running into this issue in Monterey

**Comment by JustinTowers** [comment]
had to delete vs code and reinstall

**Comment by bogu399** [comment]
I got trouble with Permissions on Windows too.
I need access to this folder, however I'm admin 
c:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench

**Comment by Unthrottled** [comment]
@bogu399 Does that directory actual exist on your computer?

**Comment by bogu399** [comment]
> @bogu399 Does that directory actual exist on your computer?

Well, I have solved restarting my PC. Everything is working fine right now 😅

**Comment by SoloLevelUp** [comment]
chown: /private/var/folders/vx/z62f6vz95zn_d6r9mhy9nnfc0000gn/T/AppTranslocation/F5321064-6247-4C25-9865-6BDC1FBE20B6/d/Visual: No such file or directory
chown: Studio: No such file or directory
chown: Code.app/Contents/Resources/app/out/vs/workbench: No such file or directory

Please help I'm getting an error trying to install the stickers on Mac (ver. Monterey) I am not a programmer (just recently started to learn) so it's hard to understand everything and resolve it myself! From my understanding the OS is preventing to modify the file/folders and is only read mode!?

**Comment by Unthrottled** [comment]
@SoloLevelUp You probably need to escape any spaces with `\ ` (I can probably add that to the thing in the help later)

Let me know if this works for you:

```bash
sudo chown -R $(whoami) /private/var/folders/vx/z62f6vz95zn_d6r9mhy9nnfc0000gn/T/AppTranslocation/F5321064-6247-4C25-9865-6BDC1FBE20B6/d/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench

```

You might get `Read-only file system` errors, like OP. 

This might be worth a try if that doesn't work https://github.com/doki-theme/doki-theme-vscode/issues/115#issuecomment-972481090

**Comment by lowqualityrkomi** [comment]
Try this.
If you have VSCode application in the Download folder, you have to move it in the Applications folder. Then you can lounch the command to set wallpaper and stiker directly from the VSCode's command palette (SHIFT+COMMAND+P).

**Comment by lowqualityrkomi** [comment]
Try this.
If you have VSCode application in the Download folder, you have to move it in the Applications folder. Then you can lounch the command to set wallpaper and stiker directly from the VSCode's command palette (SHIFT+COMMAND+P).
