### ISSUE TITLE
Questions above Glass Pane feature

### ISSUE THREAD

**Issue by abhiv27** [doki-theme/doki-theme-vscode#120]
Is there any way to turn off Glass Pane mode ?

**Comment by Unthrottled** [comment]
You should be able to remove assets from your VS Code using `Doki-Theme: Remove Sticker/Background`, is that what you were wanting to know?

**Comment by abhiv27** [comment]
Hi,
Apologies for that poorly framed question.
I just wanted to know if it is possible to unblur the wallpaper when I open any file within vscode. Is it enabled by VS Code by defualt which cannot be changed ?

For example, when I am in the home screen of Visual Studio Code, the wallpaper appears bright but as soon as I open the editor there is an amount of blur to the wallpaper.

**Comment by Unthrottled** [comment]
>I just wanted to know if it is possible to unblur the wallpaper

Ah, so the wallpaper itself is not blurred, as it is partially transparent. 
So you can fix this by providing your own custom asset to `doki.wallpaper.path` that is more opaque to your liking. [See documentation](https://github.com/doki-theme/doki-theme-vscode#custom-assets).

https://user-images.githubusercontent.com/15972415/135267380-82930936-636d-40a1-9c50-6c5484b6ff66.mp4

Is that what you where looking for?

**Comment by abhiv27** [comment]
Yes, that was exactly what i was looking for. I shall look into the documentation once again. Thanks for your help.
