### ISSUE TITLE
Wallpaper/Background (Gif) Issues VSCode

### ISSUE THREAD

**Issue by Jrock2722** [doki-theme/doki-theme-vscode#124]
Hi there! I'm in a bit of a pickle and messed with things that I probably shouldn't have 😅 
First off...I messed up the code for the extension's settings.json. Do you happen to have a spare template for the original code?

My second problem is my primary issue.  Every time I try to copy a background from my file pathway and paste it into "doki" settings, it doesn't work.

![2021-11-17 (1)](https://user-images.githubusercontent.com/81665917/142300566-1a9f1f64-fdf3-40eb-b5a6-dc7130ddaa74.png)

![2021-11-17 (3)](https://user-images.githubusercontent.com/81665917/142299787-dbb75b42-9b3a-49f2-9724-ac7284e2e74c.png)
For example, I typed in something like this into settings.json (although I'm not sure if I was pasting in the doki pathway the right may). 
"doki.background.path":"C:\\Users\\Jorda\\Downloads\nezuko-kamado-kimesu-no-yaiba-desktop-wallpaperwaifu.com.mp4"

Instead...

This screen always shows up. 

![2021-11-17 (4)](https://user-images.githubusercontent.com/81665917/142299603-8e3698f2-9493-4f41-b9db-ff3e656f2b6d.png)

Pasting the background/gif file into settings.json won't work either (part of the reason is due to messing up the settings.json code). If you will, could you help me with this issue? Thanks in advance

Also, my workbench file is this: c:\Users\Jorda\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench

**Comment by Unthrottled** [comment]
If you put this in the settings json, then you need to escape the `\` character

"doki.background.path":"C:\\Users\\Jorda\\Downloads\\nezuko-kamado-kimesu-no-yaiba-desktop-wallpaperwaifu.com.mp4"

Entering the values in through the Settings UI will automatically add the `\\` for you.

If it is something else, let me know.

**Comment by Unthrottled** [comment]
> My second problem is my primary issue. Every time I try to copy a background from my file pathway and paste it into "doki" settings, it doesn't work

If it isn't an issue with the escape characters, it is probably an issue with the file you are trying to use, `mp4` is not a supported media type for asset installation. Under the hood, backgrounds are set using the CSS `background` attribute, pretty sure that doesn't support `mp4`

**Comment by Jrock2722** [comment]
I get what you're saying. I used a jpg file this time but it still shows this:

"Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again."

I think it has to do with the json settings window code.... I messed myself up with this 😅

![Capture evi](https://user-images.githubusercontent.com/81665917/142333822-0aeb5401-9e63-4009-8f55-e2daba9aa476.PNG)

**Comment by Unthrottled** [comment]
@Jrock2722 Here's something for you https://code.visualstudio.com/docs/getstarted/settings#_common-questions

> #### How can I reset my user settings?

> The easiest way to reset VS Code back to the default settings is to clear your user settings.json file. You can open the settings.json file with the Preferences: Open Settings (JSON) command in the Command Palette (Ctrl+Shift+P). Once the file is open in an editor, delete everything between the two curly braces, save the file, and VS Code will go back to using the default values.

Based on your example all you have to do is delete the line with `"background.filepath":` and you should be good, you just made your json :cry:

**Comment by Jrock2722** [comment]
I appreciate your help anyway. I tried your options and the Doki Sticker Help window still pops up

**Comment by Unthrottled** [comment]
:thinking: 
So if your settings.json is just this

```json
{
  "doki.background.path":"C:\\Users\\Jorda\\Downloads\\\\Uraraka_Wallpaper.jpg"
}
```
It fails to install?

**Comment by Jrock2722** [comment]
Yeah, I'm still working with it atm. I'll let you know if anything changes. I went to Stackoverflow for help. Seems like other people ran into this issue similarly

**Comment by Jrock2722** [comment]
Deleted everything in my brackets too btw

**Comment by Unthrottled** [comment]
Cool, good luck. 
Make sure that:

- You have write access to ![image](https://user-images.githubusercontent.com/15972415/142338060-dae17e78-6c78-4cfe-ba8f-1a73864ac953.png) (make sure you don't need admin privileges. 
- The path specified for the asset you want to use points to a file exists, an you have read access (you don't need special privileges to read the file).
- If editing the json file directly, make sure you escape the `\` characters in the path so they become `\\`.
- Make sure that your json is well formed, if editing the settings json.


I'll add some code over this weekend to tell you if installing failed because the file specified does not exist.

**Comment by Jrock2722** [comment]
Hi there! I have returned. I don't mean to interrupt you but I just wanted to send you a video of what I did. Only this time, nothing pops up after I've pressed enter on my keyboard so many times. I used a gif btw.


https://user-images.githubusercontent.com/81665917/145661694-c69ece70-8b13-4afe-9649-aca393e8c065.mp4

**Comment by Unthrottled** [comment]
Thanks for providing the video! I think you can fix your problem by removing the `"` from the string. Here's how I did it.

https://user-images.githubusercontent.com/15972415/145680000-17d6a52f-9aeb-4e94-90a9-9e531293d57b.mp4

**Comment by Jrock2722** [comment]
I wanted to stop by and say thank you for all your help! Everything is working fine now. The only issue I have now is that the settings are "Unsupported" and I can't type anything into the terminal, but it's easily fixed by reloading the entire home screen back to its original look. Thank you again!

https://user-images.githubusercontent.com/81665917/145696056-104ba6c6-0d3d-45f3-b9cc-775625d70c8f.mp4

**Comment by Unthrottled** [comment]
Cool! Happy to help.

I think that the last issue you experienced is related to https://github.com/doki-theme/doki-theme-vscode/issues/98 , which I am currently _still_ unable to reproduce. Maybe my VSCode just likes me more? :smile: 

Will fix that issue when it starts doing it to me.
