### ISSUE TITLE
Unable to install theme!

### ISSUE THREAD

**Issue by SoloLevelUp** [doki-theme/doki-theme-vscode#127]
https://user-images.githubusercontent.com/85768946/147237614-a3eb3ecb-0647-4849-b6bf-b928017b990a.mov

Cannot install theme from command palette but it works if I manually select the theme from the Settings > Appearence > Theme! 
But I don't know how to install stickers manually though! 
OS: Mac
Doki ver. 19.0.0

**Comment by Unthrottled** [comment]
Thanks for supplying this supporting information. 

It looks like this issue is related to #115 .

Do you remember how you installed VSCode? Was it following these steps: https://code.visualstudio.com/docs/setup/mac#_installation ? 

I've also got a MacBook, and haven't had this issue, so I am curious how you got VSCode installed.

**Comment by SoloLevelUp** [comment]
@Unthrottled thank you! I followed the steps (before that I installed it by double clicking like in windows) and it's working now but I get the notifications saying
"Your Code installation appears to be corrupt. Please reinstall." It's working for now but I fear if I might lose unsaved work in the future. Let's see!

- It looks like this issue is related to #115 . 
 
I don't know how it works though! Thanks again!!

**Comment by SoloLevelUp** [comment]
(Unsupported) in the title bar and the warning redirects to this article https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported. Is it a big concern?

**Comment by Unthrottled** [comment]
The `Unsupported` is a known issue.

> Installing theme assets requires me to corrupt VS-Code by modifying CSS. You will have to use the "Remove Sticker/Background" command to restore VS Code back to supported status before uninstalling. You can close all VSCode windows and start it back up remove the annoying Unsupported warning. The plugin automatically fixes VSCode's checksums.

[Link](https://github.com/doki-theme/doki-theme-vscode#background-images)

**Comment by SoloLevelUp** [comment]
I see thanks!
