### ISSUE TITLE
Sticker/Background installation

### ISSUE THREAD

**Issue by Celestae** [doki-theme/doki-theme-vscode#129]
**Describe the bug**
 Even if I run the Visual Studio Code in Administrator, it feels like it can't write into f:\Microsoft VS Code\resources\app\out\vs\workbench.

**To Reproduce**

1. Run VS Code as administrator
2. Try to install a background
3. Unable to install ____, please see active tab for more imformation

**Expected Behavior**
 I would like the actual theme

**Environment**
 Anyone of them

**Screenshots**

![image](https://user-images.githubusercontent.com/76761076/150867825-f7fba340-9dcc-458d-8630-591164f17d4c.png)

**Comment by Unthrottled** [comment]
Is `f:\Microsoft VS Code\resources\app\out\vs\workbench` the actual installation directory on you machine?

**Comment by Celestae** [comment]
Is it supposed to direct to this?

![image](https://user-images.githubusercontent.com/76761076/150886138-f75a8d81-0f55-4da5-a829-ca434e037fa7.png)

**Comment by Unthrottled** [comment]
Yup, the extension is trying to edit the workbench.desktop.main.css file in that directory.
Is that volume read only?

**Comment by Celestae** [comment]
I've been trying to remove it all day, but it keep reverting back to read only. I guess it is what it is. Thank you for your help~

**Comment by Unthrottled** [comment]
Hey fam, I am going to assume you've got your issue fixed, if not please let me know and we can work through it some more. Thanks!
