### ISSUE TITLE
Sayori Dark not available in vscode but it's in Jetbrains IDE

### ISSUE THREAD

**Issue by Drk01** [doki-theme/doki-theme-vscode#133]
**Describe the bug**
Sayori Dark not available in vscode but it's in Jetbrains IDE
**To Reproduce**

1. Install Doki Theme in vscode
2. Install Doki Theme in Jetbrains IDE
3. Search Sayori Dark
4. Pain...

**Expected Behavior**
Please make Sayori Dark come back, she already suffered too much :broken_heart:

**Comment by Unthrottled** [comment]
Ah, she's still there

![image](https://user-images.githubusercontent.com/15972415/156842158-c2c0342b-add6-4877-93c4-0cbe91ce42e7.png)


You just have to type `Š̸̘͚̼͎̯̙̣̱̎̋̐͒a̴̖̟̠̳̤͙̟͂̂͑̐͜ỷ̵̧̨̞̠̖̠o̴̧͍̗̬̎̓͆̔͝ͅr̴̡̮̟͈͠ͅi̴̡̨͓͈̬̗̺̍́̃̇̓` 😂 

---

For real though, I'll remove the Zalgo Text, so you can just search `Sayori`.
