### ISSUE TITLE
Indent Guide Colors / Highlighting

### ISSUE THREAD

**Issue by Beardography** [doki-theme/doki-theme-vscode#135]
**Is your feature request related to a problem? Please describe.**
Thanks for the great themes! There is one issue I run into is with some longer files (like with SCSS). I rely on the indent highlighting, and currently, I don't see indent highlighting (and that might be the wrong term for it).

I think either having a color used for the indent highlighting or even changing the contrast to show the indent highlighting could be super helpful.

Here's an example of what I mean:
![2022-03-18 11_01_29-Window](https://user-images.githubusercontent.com/18759729/159040954-ee532d83-c2c0-498c-82f9-ac92b1eb7ea3.png)

I hope this helps!

Also, sorry for any confusion, this is the first issue I've ever created on here.

**Comment by Unthrottled** [comment]
Hey! Thank you for taking the time to submit this issue. 

The indent guides are that way on purpose, I like them barely visible. So I'm not going to change it for all of the themes. Thank you for understanding.


However, you can customize [the theme color](https://code.visualstudio.com/api/references/theme-color) to your tastes.

Here are the two settings that you can customize.

```
    "workbench.colorCustomizations": {
        "editorIndentGuide.activeBackground": "#00ffff",
        "editorIndentGuide.background": "#8800bb"
    },
```

![image](https://user-images.githubusercontent.com/15972415/159092855-8ca296ed-c4c4-45e6-b837-89b9a49f731f.png)

I suppose I could also add some documentation that could point out the custom color customization, if you think that would have helped you with this issue.

**Comment by Beardography** [comment]
Oh heck yeah, that's is for the heads up on how I can do that. I really appreciate it and looking forward to future releases, keep up the great work!
