### ISSUE TITLE
Cannot install wallpapers and stickers on MacBook

### ISSUE THREAD

**Issue by lowqualityrkomi** [doki-theme/doki-theme-vscode#137]
$ sudo chown -R $(whoami) /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual\ Studio\ Code.app/Contents/
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//Frameworks/Code Helper (Renderer).app: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//Frameworks: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//Info.plist: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents//PkgInfo: Read-only file system
chown: /private/var/folders/f_/cg4btzl157g82fwwyr4h_xzh0000gn/T/AppTranslocation/CED52DF3-3FBE-4E4D-9A89-A95102B61BB6/d/Visual Studio Code.app/Contents/: Read-only file system

**Comment by lowqualityrkomi** [comment]
If you have VSCode application in the Download folder, you have to move it in the Applications folder. Then you can lounch the command to set wallpaper and stiker directly from the VSCode's command palette (SHIFT+COMMAND+P).

**Comment by Unthrottled** [comment]
This seems like it is related to #115 . 

I'll add a reference to this issue in the `Help Page` in the extension. Thanks for the supporting information!

**Comment by Unthrottled** [comment]
@Balenciag 

Can you follow these steps and provide the output from this comment: https://github.com/doki-theme/doki-theme-vscode/issues/172#issuecomment-1220510722 ?

**Comment by gfrewqpoiu** [comment]
For anyone that stumbles upon this from the link in the extensions help page:
If the App is already in `/Applications` , but you still get this issue, where the app path includes `.../AppTranslocation/...` which is read only, then the app is quarantined by macOS, this can happen when installing through Homebrew (Cask).

To fix this, run this command in a shell (replacing Code.app with the name of the App):
`sudo xattr -r -d com.apple.quarantine /Applications/Code.app`
and then restart VSCode and try to install the sticker or background again.
