### ISSUE TITLE
Images don't show

### ISSUE THREAD

**Issue by dowoma** [doki-theme/doki-theme-vscode#145]
I'm new to VS Code and I've read the documentation multiple times so I'm not sure if I'm missing something and there's something I need to do but the sticker and wallpaper won't show up for me. I've tried installing then closing and opening vs code and uninstalling and trying again. I checked in settings if I need to toggle something but I don't see anything. I apologize if there's an answer for this somewhere. Help would be appreciated as I think this is super cool! Thanks.

![image](https://user-images.githubusercontent.com/73277829/167819926-ff1fa6ac-c9fa-4e83-832b-e1b5f16259d9.png)

**Comment by Unthrottled** [comment]
Does following these steps not work for you? (I'm on a Mac, but windows shouldn't be much different)

https://user-images.githubusercontent.com/15972415/167829322-c1c5e2a6-2caf-4c91-a3e7-1adc89ba58eb.mp4

**Comment by dowoma** [comment]
> Does following these steps not work for you? (I'm on a Mac, but windows shouldn't be much different)
> 
>  doki-vscode-install.mp4

That worked! Thank you so much. I didn't know we had to do it from the command palette. Still new to VS Code. <3
