### ISSUE TITLE
How to use only one of the funds

### ISSUE THREAD

**Issue by ATSxp** [doki-theme/doki-theme-vscode#147]
I wanted to ask a question.

How can I use only one of the funds? For example:

I don't want to use the background from "doki-background.path", I just want to use the background from "doki-wallpaper.path".

So I wanted to know if there is a way to use just one of these funds, because when I use one of them,
the other ends up being forced to use one of its images from the extension.

Hope you can help me =)

**Comment by Unthrottled** [comment]
Just so I am clear, you want to be able to only want to have an image drawn on the code and nothing drawn in the background when all code editors are closed?

**Comment by ATSxp** [comment]
yes

**Comment by Unthrottled** [comment]
Ah, okay. Yeah there isn't a first class supported way.

A hack would to set `doki-background.path` to a transparent image like this one.
![HD_transparent_picture](https://user-images.githubusercontent.com/15972415/168489275-b52e9e62-233c-41f3-89ad-bb77342b040c.png)

When I get the time later this month, I'll revisit this, but that's your work around for now. Thanks!

**Comment by ATSxp** [comment]
Okay thank you so much =)
