### ISSUE TITLE
Wallpapers and stickers are not displayed after downloading it

### ISSUE THREAD

**Issue by Yqno** [doki-theme/doki-theme-vscode#148]
I Use Ubuntu 20.04.4 LTS x86_64 in a Docker Container and Every time I want to download stickers or Wallpapers nothing happened, I cleared the Cache and use the sudo commands, and reinstall so many times and even there nothing happened

https://user-images.githubusercontent.com/79216939/169813468-3b71061f-ab59-4952-ad6f-f48945c0e353.mp4

>

**Comment by Unthrottled** [comment]
>in a Docker Container 

Are you running Visual Studio Code in a container?

I saw this:

<img width="241" alt="Screen Shot 2022-05-23 at 5 51 08 PM" src="https://user-images.githubusercontent.com/15972415/169917217-d8f940fa-f04a-431c-be11-60216fd44b75.png">

Are you connected to something remote? If so could you disconnect, try to install. Might be related to this https://github.com/doki-theme/doki-theme-vscode/issues/32#issuecomment-727662939 (however that might be something .net related, I dunno, just trying to guess why the installation failure stuff isn't working)

If you are feeling extra explorative. You can use the `Show Logs` in the command palette or Help -> Toggle Developer tools, to investigate the issue more. Thanks!

https://user-images.githubusercontent.com/15972415/169917950-8a842e0d-1d9d-43fa-bfc8-5e6ea5326e91.mp4

**Comment by Yqno** [comment]
The remote connection is from the remote server that runs the docker Container

**Comment by Yqno** [comment]
and the logs show me only this messages 
![image](https://user-images.githubusercontent.com/79216939/169987030-487f5655-abb1-416c-9158-88916b6d6dd0.png)

**Comment by Unthrottled** [comment]
Ah so it looks like you are running VS Code from a Code Server. Your current VS Code is acting like a thin client (ui). The guts of the VS Code is running in the background. (Related comment https://github.com/doki-theme/doki-theme-vscode/issues/131#issuecomment-1048318341) 

I've got code that should install things on a code-server, but it appears like it isn't working as expected. Let's try something.

Could you disconnect your VS Code, then try to install the assets?

You should be able to click this and choose disconnect from the command palette. 

<img width="241" alt="Screen Shot 2022-05-23 at 5 51 08 PM" src="https://user-images.githubusercontent.com/15972415/169917217-d8f940fa-f04a-431c-be11-60216fd44b75.png">

**Comment by Yqno** [comment]
Nope, Nothing happened, and I don't have access to the server, only to the Container

**Comment by Unthrottled** [comment]
Bummer, well could you attempt to install the asset(s) then could you please provide all the logs? Asset installation not working, and I don't know enough about your environment to reproduce the issue.

**Comment by Yqno** [comment]
I only see the stickers on the Help asset tab and I only see this logs, and it doesn't change when I install an asset 
![image](https://user-images.githubusercontent.com/79216939/170150349-8b8c3fe8-ef52-4bd1-94eb-a1c2000ef133.png)

**Comment by Yqno** [comment]
![image](https://user-images.githubusercontent.com/79216939/170221308-ac7ab3ad-4ebe-4469-9b8e-35309cab53a7.png)
and on my phone i see all from the doki theme

**Comment by Yqno** [comment]
Now i see all and when i want to remove backround and sticker both remains

**Comment by Unthrottled** [comment]
Ah, I think I understand your set up more.

You have a remote server that is running the code server.

You access your VS Code through the browser.

So, I think most of your issues (with it not showing up) might be stemming from the browser caching CSS (Since it shows up on your phone). Try clearing your caches for that site and reload.

**Comment by Yqno** [comment]
Yes, thanks, the problem is fixed
