### ISSUE TITLE
Method calls on numeric literals are rendered as strikethrough

### ISSUE THREAD

**Issue by aliceif** [doki-theme/doki-theme-vscode#149]
**Describe the bug**
In a C# file, any method calls on a numeric literal are rendered with strikethrough for some reason.
This differs from the default vscode styles and from the doki themes for VS2022 so i assume it is unintentional.

**To Reproduce**
1. Create an empty C# file
2. Add a line: `System.Console.WriteLine(1.23.ToString());`

**Expected Behavior**
Have syntax rendering that follows established patterns.

**Environment**
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

Doki Theme v78.1.4

**Screenshots**
VSCode Darkness-Dark
<img width="353" alt="image" src="https://user-images.githubusercontent.com/7098860/170240830-1e278962-8071-4516-8c76-4774c1adba06.png">

VS2022 Darkness-Dark
<img width="340" alt="image" src="https://user-images.githubusercontent.com/7098860/170240897-78de174b-a9c6-4f0c-a3aa-0b661e86785a.png">

VSCode built-in
<img width="345" alt="image" src="https://user-images.githubusercontent.com/7098860/170241001-c060b6ad-83cd-47d3-9de4-1fea721ac4e9.png">

**Comment by Unthrottled** [comment]
I think the strike through might be intentional. My VS Code is saying that is _invalid_.

<img width="1136" alt="Screen Shot 2022-05-25 at 5 12 06 PM" src="https://user-images.githubusercontent.com/15972415/170376400-3eb811f7-3029-4945-8362-88a85871a43c.png">


Here is what what I did.

1. Put my caret over the token I wanted to inspect
2. Ran `Developer: Inspect Editor Tokens And Scopes` in the command palette

Can you confirm that you also get?


title | value
-- | --
textmate scopes | invalid.illegal.constant.numeric.cssource.cs
foreground | invalid

If so then that is the expected behaviour, unless I need to install a plugin. I installed the c# plugin but still got this.

**Comment by aliceif** [comment]
Ok, with the .ToString example it lines up exactly with what I see - the popup is identical. Must be a mistake in Visual Studio Code's tokenization then - calling a method on a number in C# is 100% valid.

In another case there is seemingly a difference - I defined an extension method for the integer type and with the doki theme it gives me this:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/7098860/170379586-3e2ee060-e73d-46ce-bb2c-2d7d49f961e7.png">
But with the default dark theme I get this:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/7098860/170379767-bdea0e71-2798-4c2f-b628-bf431a868ddb.png">
Which has a "semantic token type" entry.
To be honest I don't know anything about color theme development and if this is in any way significant - it seems like the invalid.illegal.constant.numeric thing is the root cause.

 Thanks for the guidance, I think this issue can be closed since this doesn't look like a problem here specifically.

**Comment by Unthrottled** [comment]
Got it! That's a shame, if they eventually fix the [token parsing stuff](https://code.visualstudio.com/api/language-extensions/overview), I'll be happy to make sure it is themed correctly.

I'll leave you with a hacky workaround.

Just plop this into your `settings.json` file, and it will override the incorrect behaviour. So your thing that is wrong will look right. Whether you are ready for it to come back and bite you in the future is up to you 😄 

```javascript
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": [
					"invalid.illegal.constant.numeric.cs"
				],
				"settings": {
					"foreground": "#8097E3",
					"fontStyle": ""
				}
			},
		]
	},
```

<img width="1136" alt="Screen Shot 2022-05-25 at 6 40 07 PM" src="https://user-images.githubusercontent.com/15972415/170386810-11e37699-69b5-423e-802e-0b36c6106288.png">
