### ISSUE TITLE
Some suggestions...

### ISSUE THREAD

**Issue by ATSxp** [doki-theme/doki-theme-vscode#150]
**Is your feature request related to a problem? Please describe.**

1 - When I add my own wallpaper, the VS terminal letters are on the bottom of the wallpaper (thus, forcing the user to show the image).
(This also goes for the list of intellisense variables
and the scrollbar with zoom out on the side);

2 - Give us the option to change the name that is in the lower right corner of the bottom bar of VS (where the heart is);

**Describe the solution you'd like**

1 - Find a way for the wallpaper to be under the letters;

2 - Option to change the name :/

**Describe alternatives you've considered**

1 / 2 - It's already described =)

**Additional context**

I also want to add a compliment to this beautiful work that you did 'v'

**Comment by Unthrottled** [comment]
> 1 - When I add my own wallpaper, the VS terminal letters are on the bottom of the wallpaper (thus, forcing the user to show the image).
(This also goes for the list of intellisense variables
and the scrollbar with zoom out on the side);

Yeah it's going to stay that way, not changing that. 

The way it works right now is that the image itself is transparent. Example:

![Nao Light](http://doki.assets.unthrottled.io/backgrounds/wallpapers/transparent/nao_light.png)

Here is a [simple guide in GIMP, on how to change the opacity of an image/layer](https://thegimptutorials.com/how-to-change-opacity/) which you can use to make your image transparent. [Here is where you can get GIMP](https://www.gimp.org/)

> 2 - Give us the option to change the name that is in the lower right corner of the bottom bar of VS (where the heart is);

Yeah, I'll do that, might be a little bit, I want to finish what I am working on right now.

**Comment by ATSxp** [comment]
Thank you very much for answering me.

Thank you for your presentation about GIMP, I already use it and since the situation of the lyrics will be like this... it's ok

And as for the name in the corner, I'm glad to read that you'll be working on this mechanic in the future.

great job ;)

**Comment by Unthrottled** [comment]
Happy to help, I'll leave this open so I don't forget about feature 2, when I come back to updating this project..

**Comment by Raunakrs** [comment]
I can't download sticker/wallpaper..?
It says network connection error...
I'm new to coding and started learning a week ago.
