### ISSUE TITLE
Invisible terminal text

### ISSUE THREAD

**Issue by Dialvehid** [doki-theme/doki-theme-vscode#155]
**Describe the bug**
Terminal text turns invisible after setting custom wallpaper/background

**To Reproduce**
1. Set custom Doki-Theme color theme
2. Set custom wallpaper & backgound path using the "Extension Settings" option
3. Reload window
4. Open terminal

**Expected Behavior**
The Terminal will open normally and display text but will be covered by background/wallpaper, so its possible to copy text from terminal and use it but it is not visible until you copy it on the text editor

**Environment**
Versión: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Fecha: 2022-06-14T12:48:58.283Z
Electrón: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
Doki-Theme version: v78.1.5

Before setting background/wallpaper path
![image](https://user-images.githubusercontent.com/47506679/174499849-cf54c325-38ab-4bb0-abdc-0e1f88d1629e.png)

After setting background/wallpaper path
![image](https://user-images.githubusercontent.com/47506679/174499933-5b1e0510-ff03-4d68-82c5-2444908c386b.png)

**Comment by Unthrottled** [comment]
Hey! 

This is a know issue [please see this comment](https://github.com/doki-theme/doki-theme-vscode/issues/150#issuecomment-1140349756)

Is there something I could add to the [custom assets documentation](https://github.com/doki-theme/doki-theme-vscode#custom-assets) that would have helped you?

**Comment by Dialvehid** [comment]
Hi there, thank you for your answer 

The linked comment was very helpful thank you very much

As for something else to add to documentation, a warning about the consequences of not getting a transparent image would be the best option, in my opinion

love your work 👍
