### ISSUE TITLE
I need more walpapers

### ISSUE THREAD

**Issue by VISOSO2403** [doki-theme/doki-theme-vscode#157]
i need nagatoro wallpaper, anime: nazo no kanojo x.
It's not a problem but as an otaku, it would be a very good wallpaper

**Comment by Unthrottled** [comment]
Hey! So you have the ability to set your own assets. See the [custom assets](https://github.com/doki-theme/doki-theme-vscode#custom-assets) portion of the documentation. 

Please be aware of this issue https://github.com/doki-theme/doki-theme-vscode/issues/155 when setting custom assets. I haven't updated the documentation yet.

 You are also welcome to submit a [theme request](https://github.com/doki-theme/doki-master-theme/issues). The list keeps growing though 😅 
 
 I think that covers what you are asking. Thanks!
