### ISSUE TITLE
Wallpaper Overlapping(Windows)

### ISSUE THREAD

**Issue by kmadhav907** [doki-theme/doki-theme-vscode#158]
**Describe the bug**

Wallpaper of the editor keeps overlapping on the selected tab on the settings and other places like Version Control
**To Reproduce**

1. After running the VSCode as Admin,  install the extension and set the Wallpaper
2. Wallpaper Keeps overlapping on various tabs

**Expected Behavior**

It should not overlap on the tabs
**Environment**
 For all Themes

**Screenshots**

![image](https://user-images.githubusercontent.com/54632221/178044170-0946d919-13d4-42a1-8d4b-e3c6f2f7e33c.png)

**Comment by Unthrottled** [comment]
Did the problem fix itself or do you just not care anymore?

Just checked on 

```
Version: 1.69.0
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:46.408Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
```

And the settings appears to be okay

<img width="1136" alt="Screen Shot 2022-07-09 at 8 35 23 AM" src="https://user-images.githubusercontent.com/15972415/178108175-947d9ec8-ba32-4247-ae70-4b29d0b356df.png">

**Comment by kmadhav907** [comment]
Well yes I was apparently using old version of VSCode

**Comment by Unthrottled** [comment]
Aight, thanks for the follow up. :)
