### ISSUE TITLE
Dart language syntax highlighting

### ISSUE THREAD

**Issue by leoshusar** [doki-theme/doki-theme-vscode#159]
Hi! I just found this great theme collection, I'm happily using it in VS and I also wanted to use it in Code.
However Dart doesn't have full syntax highlighting, many tokens are just white.
See the example.
Default:
![image](https://user-images.githubusercontent.com/13891066/178115674-254c0da7-1362-4e45-85bc-db881822d6a8.png)

Essex:
![image](https://user-images.githubusercontent.com/13891066/178115667-4c271fac-a45c-40b5-bdca-9f9652aaa0b5.png)

Rei:
![image](https://user-images.githubusercontent.com/13891066/178115703-7ea27afa-2fc6-4a81-ab6b-836c51b812ea.png)

I'm not sure if this is a bug or a feature request, maybe it's necessary for Dart to add some special mapping or something? Could you please look at it?
Thank you!

**Comment by Unthrottled** [comment]
Sure, I'll add that when I get around to updating this plugin.

Do you have a sample dart codebase I could use?

**Comment by leoshusar** [comment]
Great! I currently don't have my own, but I found [this] (https://github.com/apgapg/rx_dart_samples/tree/master/lib) might be enough.

**Comment by Unthrottled** [comment]
Hey! So I almost got it all complete, the version I just released should have most of the fixes.

However, it will not be enabled by default until #160 is in.

Until then, just put this line in your settings json

```
	"editor.semanticHighlighting.enabled": true,
```

and the syntax highlighting for Dart files should be more colorful 🎨

**Comment by leoshusar** [comment]
I just tried it, looks like it's working:
![image](https://user-images.githubusercontent.com/13891066/179474720-9f3d273c-9ac6-42e2-b24a-29a4232afe26.png)

Looks great! Thanks for the update!
