### ISSUE TITLE
Wallpaper/sticker installation on ``code-server`` (yarn) fails

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [doki-theme/doki-theme-vscode#164]
**Describe the bug**

When you try to install the wallpaper/background on a ``code-server`` install (installed using ``yarn``), the installation fails despite doing the following command below:
```
sudo chown -R $(whoami) /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench
```

**To Reproduce**

1. Install ``code-server`` and the extension
2. Try to install a custom wallpaper/sticker

**Expected Behavior**

Installation to complete after giving chown permissions

**Environment**

OS: Android 12 (ARM64)
VSCode ver: v1.68.1
code-server ver: v4.5.1
Installed using yarn
Doki-theme: v84.1.6

**Screenshots**

![Screenshot_20220722-074505_Brave](https://user-images.githubusercontent.com/30568955/180338821-2150791f-1982-4546-b1b4-e844a72a8365.jpg)

**Comment by Unthrottled** [comment]
Just curious, do you have write access to 

```
/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench
```

after running the command? (eg. can you add files & write to existing files in that directory?

**Comment by RealEthanPlayzDev** [comment]
@Unthrottled Yes, I can.
![Screenshot_20220723-013804_Termux](https://user-images.githubusercontent.com/30568955/180502850-2590e856-079a-471e-b829-05fbdb5a9c1f.jpg)

**Comment by Unthrottled** [comment]
🤔 Okay, I'll have some time later to try this out. 

However, it would be a _huge_ help if you could provide logs from your visual studio code, when running the asset installation command(s). You can see an example of how to view all the visual studio code logs in this comment https://github.com/doki-theme/doki-theme-vscode/issues/148#issuecomment-1135216585

**Comment by RealEthanPlayzDev** [comment]
> However, it would be a huge help if you could provide logs from your visual studio code, when running the asset installation command(s). You can see an example of how to view all the visual studio code logs in this comment https://github.com/doki-theme/doki-theme-vscode/issues/148#issuecomment-1135216585

[RemoteExtensionHostLog.txt](https://github.com/doki-theme/doki-theme-vscode/files/9173087/RemoteExtensionHostLog.txt)
[RemoteServerLog.txt](https://github.com/doki-theme/doki-theme-vscode/files/9173088/RemoteServerLog.txt)
[WindowLog.txt](https://github.com/doki-theme/doki-theme-vscode/files/9173089/WindowLog.txt)
[WorkerExtensionHostLog.txt](https://github.com/doki-theme/doki-theme-vscode/files/9173090/WorkerExtensionHostLog.txt)

**Comment by Unthrottled** [comment]
Thanks! I was hoping those would be more helpful. Anyways I'll have time later (maybe this coming weekend 🤷 ) to look into reproducing the issue.

If you _really_ want custom assets, I think a variant of this https://github.com/doki-theme/doki-theme-vscode/issues/121#issuecomment-1003196138 could help. I know this works on-code server, I just don't know why it's being a jerk with the yarn install.

**Comment by RealEthanPlayzDev** [comment]
> If you really want custom assets, I think a variant of this #121 (comment) could help

Unfortunately I'm on mobile so using Stylus isn'r possible

Either way I'll just wait for it to be resolved, thanks for responding!

**Comment by Unthrottled** [comment]
I was able to replicate the issue and get a fix in.

After you install your assets, you'll need to hard refresh (clear caches & reload) your browser window. That way the VSCode css with the custom assets gets picked up.

I'll have the extension published probably later today, working on another change before I release.

**Comment by RealEthanPlayzDev** [comment]
Oh okay, thank you for solving this :+1:

**Comment by Unthrottled** [comment]
@RealEthanPlayzDev I've published the plugin to the vsx repository https://open-vsx.org/extension/unthrottled/doki-theme so the fix should be available now, thanks for waiting!
