### ISSUE TITLE
Wallpaper installed with a command overlays the custom wallpaper.

### ISSUE THREAD

**Issue by Gianka1485** [doki-theme/doki-theme-vscode#167]
**Describe the bug**
The problem is that when setting a custom wallpaper, but before that you installed a wallpaper with some command (with the option of Ctrl + Shift + P and then type "doki" to get the recommendations), then the wallpaper installed with the command overrides the custom wallpaper, it only happens when all Visual Studio Code windows are closed.

**To Reproduce**

1. Install the Doki theme.
2. Install a wallpaper with a command (Ctrl + Shift + P , then as a command any wallpaper: Doki-Theme: Install Aqua's Wallpaper).
3. Go to the extension settings, and configure in the custom wallpaper folder location, put the desired image: C:\Users\User\Images\img.jpg
4. Then close any files you've opened with Visual Studio Code and see.

**Expected Behavior**
Keep seeing the personalized image.

**Environment**
* Windows 10 21H2
* Visual Studio Code version: 1.69.2 (user setup)
* The Doki Theme version: v84.1.6

**Screenshots**

![image](https://user-images.githubusercontent.com/89715927/182516307-a44bdb07-1726-4c98-a9f1-7edd719057a0.png)

![image](https://user-images.githubusercontent.com/89715927/182516371-0e19f7f2-d5f7-4ec9-8807-6d0b427776da.png)

**Extra data**
The error continues even if I remove the extension, use the remove wallpaper command, uninstall Visual Studio Code, or install a new wallpaper.

**Comment by Unthrottled** [comment]
Not quite sure I follow your issue.

[Custom Assets](https://github.com/doki-theme/doki-theme-vscode#custom-assets) allow you to set the `Wallpaper` & `Background`.

The `Wallpaper` displays over the code (what you've set in your custom assets)

The `Background` displays an image when all your tabs are closed

<img width="1070" alt="Screen Shot 2022-08-03 at 5 14 45 AM" src="https://user-images.githubusercontent.com/15972415/182584385-451c56f1-3037-4977-89c9-0957cbf83fcc.png">

☝️ A custom setting you haven't set. The plugin will provide the last image you've installed as the background if a custom one isn't provided. 

This is the expected behavior. 

Am I misunderstanding your issue?

**Comment by Gianka1485** [comment]
What a mistake on my part, I hadn't noticed... an apology, but then, a REAL error is that when uninstalling the extension the wallpaper remains (although I haven't thoroughly checked how to make the error, it happened to me that uninstalling the extension and reinstalling it sometimes did not remove the wallpaper).

**Comment by Gianka1485** [comment]
Another minor mistake to note is that sometimes the wallpaper is located in places that I think are not necessary, and that makes the image look distorted.

Sample:
![image](https://user-images.githubusercontent.com/89715927/182693052-aadf894c-25cf-4541-980a-95a81d151c4a.png)

Featured parts:
![image](https://user-images.githubusercontent.com/89715927/182693166-f5cd5066-18ef-409e-8b54-26a04156754e.png)

How it should look like:
![image](https://user-images.githubusercontent.com/89715927/182693423-ee5c2f9b-38f3-4315-bbb1-4c044667af13.png)

**Comment by Unthrottled** [comment]
> but then, a REAL error is that when uninstalling the extension the wallpaper remains (although I haven't thoroughly checked how to make the error, it happened to me that uninstalling the extension and reinstalling it sometimes did not remove the wallpaper).

That's a known issue, and you were prompted before you installed content that it _would_ remain after uninstalling. See this for more details https://github.com/doki-theme/doki-theme-vscode/issues/41#issuecomment-765735759

> Another minor mistake to note is that sometimes the wallpaper is located in places that I think are not necessary, and that makes the image look distorted.

Yeah that happens some times when VS code updates their CSS, when I get around to updating the plugin, I'll try to fix those.
