### ISSUE TITLE
Setting custom assets paths to a directory causes asset install issues. 

### ISSUE THREAD

**Issue by OS-dharmik** [doki-theme/doki-theme-vscode#172]
**Describe the bug**

in the asset help sectioin you say that running as administrator in wondows will fix the issue unable to install Zero Two Dark Obsidian, please see active tab for more information. but even i run it as administrator in doesn't solve I keep trying to add my own background and sticker but it keeps showing the same thing please help

**To Reproduce**

1.

**Expected Behavior**

**Environment**

**Screenshots**

**Comment by OS-dharmik** [comment]
![Screenshot (104)](https://user-images.githubusercontent.com/101666812/185327384-e0b4af48-7dad-4cee-a94c-8f66f4719bc8.png)
as you can see in the image I am running VS code as an administrator but it still shows that same error when I try to use wallpaper or stickers.

**Comment by OS-dharmik** [comment]
please help...

**Comment by Unthrottled** [comment]
> I even made sure that there is a directory as mentioned in path which I selected in the picture above.

What files are in that directory? 

Does it look anything like this? https://github.com/doki-theme/doki-theme-vscode/issues/61#issuecomment-820768870

**Comment by OS-dharmik** [comment]
> > I even made sure that there is a directory as mentioned in path which I selected in the picture above.
> 
> What files are in that directory?
> 
> Does it look anything like this? [#61 (comment)](https://github.com/doki-theme/doki-theme-vscode/issues/61#issuecomment-820768870)

yea although it had an extra folder named api the rest of the directory was the same as in the image

**Comment by OS-dharmik** [comment]
and ofcourse i tried to download it from command pallet

**Comment by Unthrottled** [comment]
That's curious, everything should be in place. 

Can you perform an asset install (like installing a sticker) and collect the logs like this?

You'll need to open the logs and developer tools, then run the install command.

https://user-images.githubusercontent.com/15972415/185598623-f6fcd0ff-3d06-41fb-9a8b-52994a484e53.mp4

This should be able to tell me where it is having an issue.

**Comment by OS-dharmik** [comment]
so, I did as you said and here are the screenshots,
![Screenshot (108)](https://user-images.githubusercontent.com/101666812/185729311-55056373-0377-4989-8c39-60988bfc5137.png)
![Screenshot (109)](https://user-images.githubusercontent.com/101666812/185729313-3b15bd3b-b6ac-44d7-b336-221234eab2ca.png)
![Screenshot (110)](https://user-images.githubusercontent.com/101666812/185729314-2e2ea55d-2250-4930-81b2-2da8145745c1.png)
![Screenshot (111)](https://user-images.githubusercontent.com/101666812/185729315-7fdb820e-2c13-4393-8123-7ee8299314b7.png)
![Screenshot (112)](https://user-images.githubusercontent.com/101666812/185729317-ac7b5b08-e286-439c-9c14-d1b6ff7eef19.png)

**Comment by Unthrottled** [comment]
> I keep trying to add my own background and sticker but it keeps showing the same thing please help

Ah you put all your information in the title.

The error says that it is trying to read an image from a directory.

Please clear out the `doki.wallpaper.path`, `doki.background.path` and `doki.sticker.path` in the settings. **or** make the paths to an actual **file** and not a **directory**.

<img width="1136" alt="Screen Shot 2022-08-20 at 7 10 05 AM" src="https://user-images.githubusercontent.com/15972415/185745547-7d8f6ca2-944c-492d-8dbf-b0b4cd26feeb.png">

The custom assets paths takes precedence over the asset install.

once you do that, your sticker/wallpaper install commands will work as expected.

I'll eventually add something that doesn't attempt to install if the custom asset path is a directory.

**Comment by OS-dharmik** [comment]
mannn !!!! thanks it is now all good and the best way it can be.it's all solved now... thank you and I hope that you keep up the good work

**Comment by ArthourVaSa** [comment]
Hi, I tried to do everything what you are saying, but it's not working for me. I have my macbook pro and I can't install the Zero Two Roses Wall Paper
