### ISSUE TITLE
I can't see anything in the terminal

### ISSUE THREAD

**Issue by Ghoul-py** [doki-theme/doki-theme-vscode#175]
**When i use custom assets i can't see the output  in the terminal**

![testfile py - 3 File   Exception - Visual Studio Code 9_29_2022 1_41_17 AM](https://user-images.githubusercontent.com/113824073/192984139-5b55682a-e78f-4def-94c1-4f3c9f1e9679.png)

**Comment by Unthrottled** [comment]
If you uninstall all the assets, does the text show up again?
Does the text show up if you use one of my themes?
Do you use any custom workbench colorization?
Also what version of VSCode are you using?
Is your image transparent enough?


<img width="1136" alt="Screen Shot 2022-09-29 at 5 17 08 AM" src="https://user-images.githubusercontent.com/15972415/193006108-2d03826b-d237-448d-bff4-0b9064de89a9.png">

```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```
Installing custom assets is no different that the assets provided by the plugin.

**Comment by Ghoul-py** [comment]
> The text show up when i use your themes

**Comment by Ghoul-py** [comment]
> > The text show up when i use your themes

**Comment by Ghoul-py** [comment]
> If you uninstall all the assets, does the text show up again? Does the text show up if you use one of my themes? Do you use any custom workbench colorization? Also what version of VSCode are you using? Is your image transparent enough?
> 
> <img alt="Screen Shot 2022-09-29 at 5 17 08 AM" width="1136" src="https://user-images.githubusercontent.com/15972415/193006108-2d03826b-d237-448d-bff4-0b9064de89a9.png">
> 
> ```
> Version: 1.71.2
> Commit: 74b1f979648cc44d385a2286793c226e611f59e7
> Date: 2022-09-14T21:07:15.900Z
> Electron: 19.0.12
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Darwin arm64 21.6.0
> Sandboxed: No
> ```
> 
> Installing custom assets is no different that the assets provided by the plugin.

Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

1) when i use your theme the text show up
2) i am not using any workbench colorization
3) i applied an overlay on the image with opacity of 0.8 and the image itself is not transparent
