### ISSUE TITLE
Sticker should appear behind Notifications Panel

### ISSUE THREAD

**Issue by nickclark2016** [doki-theme/doki-theme-vscode#176]
**Describe the bug**
When viewing notification panel, sticker appears over the panel, obstructing view.

**To Reproduce**

1. Use sticker
2. Produce a notification
3. Open notification

This is actually an issue for all tooltips from the bottom status bar in addition to the notification panel.  These should appear in front of the sticker.

**Expected Behavior**
When opening or viewing notifications, tooltips, etc., I expect the sticker to behind the tooltip and/or panel.

**Environment**
![image](https://user-images.githubusercontent.com/17892116/194655687-facfac54-f64d-4084-9c6b-d21e73048119.png)

It should contain:
* OS - Windows 11 Pro, Build 22000.978
* Product - Visual Studio Code

Please also include the Doki-Theme version
v88.1.7

**Screenshots**
![image](https://user-images.githubusercontent.com/17892116/194656458-f1b308b5-a284-47d8-8de5-efb25daadd12.png)

**Comment by Unthrottled** [comment]
Ah yeah that.

I got it to be behind one set of notifications, however I cannot remember why I couldn't get it behind those notifications. I'll look and try to see if I cannot get it behind those notifications.
