### ISSUE TITLE
The content of the terminal is not visible

### ISSUE THREAD

**Issue by Gianka1485** [doki-theme/doki-theme-vscode#178]
**Describe the bug**
It turns out that when you put a personalized wallpaper the content of the terminal is not seen, in other words, what is written in the terminal is not seen, but you can continue interacting with the terminal.

**To Reproduce**

1.Put a custom wallpaper.

2.Open the terminal.

**Expected Behavior**
The terminal should show up as normal.

**Environment**
The content of the terminal cannot be seen.

It should contain:

Versión: 1.72.0 (system setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Electrón: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
In isolated space: No

**Screenshots**

![image](https://user-images.githubusercontent.com/89715927/194796208-45b24c3e-3493-4fe3-bf82-e925cfe47303.png)
![image](https://user-images.githubusercontent.com/89715927/194796394-c7d3d28c-bfae-4b9c-ae63-28654cfd146f.png)

**Comment by Unthrottled** [comment]
<img width="1136" alt="Screen Shot 2022-10-10 at 5 20 58 AM" src="https://user-images.githubusercontent.com/15972415/194845158-492659fc-b620-4fc0-9251-914d6dd4f8a9.png">

```
Version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:19:55.212Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

I am unable to reproduce.

- Does this only happen with custom assets? (you showed the bundled assets working) 
- Have you tried other images?
- Does the terminal text show up if you use one of my color schemes (https://github.com/doki-theme/doki-theme-vscode/issues/175#issuecomment-1262073499)

I'll try maybe this weekend to look on my windows machine, to see if I cannot reproduce.

**Comment by Gianka1485** [comment]
Thanks for the recommendations, turns out I wasn't using an image with transparency, it always happens with all images without transparency.

**Comment by KeidsID** [comment]
Do Opacity and Transparancy diffrent?

**Comment by Unthrottled** [comment]
@KeidsID They represent the same concept.

Opacity: More opacity, the less you can see through it.
Transparency: More transparency, the more you can see through it.

**Comment by Huzaifa-31** [comment]
I am having this same issue , I have use transparent Image , still same issue
