### ISSUE TITLE
Customizing stickers

### ISSUE THREAD

**Issue by JackGiffordRA** [doki-theme/doki-theme-vscode#18]
-Resize stickers (in both places)
-Disable stickers in one location (Maybe I want homescreen Rem, but not over the code)

Not sure if this is possible, but
-Replace the sticker images with your own?

**Comment by Unthrottled** [comment]
Hey @JackGiffordRA ! Thank you for your interest.

:thinking: It looks like you want to use:

https://github.com/shalldie/vscode-background

Already does. It allows you to specify your own image on the editor.

It does not allow you to customize the home screen. **However**, I can submit a PR to add that and maybe it will accepted.

Sound good?

**Comment by JackGiffordRA** [comment]
Hey, thanks, that's exactly what I was looking for. In my head I was thinking about some kind of config just for the doki-theme stuff, but I suppose why reinvent the wheel when there's another extension that can handle that separately. Thanks!
