### ISSUE TITLE
Requesting pokemon theme

### ISSUE THREAD

**Issue by sandy3002** [doki-theme/doki-theme-vscode#181]
I would love to see a pokemon related theme ( actually pokegirl centric)

I don't have much knowledge of js, but could help you by supplying photos or gifs. Kindly give it a thought.

**Comment by Unthrottled** [comment]
Hey!

Thanks for the interest. I've already got my hands full with 88 themes, however [submitting a theme request is free](https://github.com/doki-theme/doki-master-theme/issues).

You can always customize your VSCode with [the custom assets feature of the plugin.](https://github.com/doki-theme/doki-theme-vscode#custom-assets)

For inspiration, you can check out this existing Pokemon theme for [hyper.js](https://hyper.is) https://github.com/klaussinani/hyper-pokemon#--hyper-pokemon

Thanks for the interest!
