### ISSUE TITLE
Help setting custom wallpaper.

### ISSUE THREAD

**Issue by zen375dragon** [doki-theme/doki-theme-vscode#185]
I've tried to follow the instructions for setting a custom wallpaper for a theme, but I can't get it to work. Could the method be re-explained please?

**Comment by Unthrottled** [comment]
You need to use the `full path` to the asset you want to use (eg `C:\Users\...` or /Users/....`), then go to the settings, search for `Doki` and put the full path in correct setting. If it was successful, the plugin will prompt you to reload.  **Make sure your wallpaper is transparent otherwise your terminal will NOT work**.

Here is a video


https://user-images.githubusercontent.com/15972415/202740915-adf973ed-432b-472e-ab3f-cd15479aaa2c.mp4

That help?

**Comment by zen375dragon** [comment]
> You need to use the `full path` to the asset you want to use (eg `C:\Users\...` or /Users/....`), then go to the settings, search for `Doki` and put the full path in correct setting. If it was successful, the plugin will prompt you to reload. **Make sure your wallpaper is transparent otherwise your terminal will NOT work**.
> 
> Here is a video
> 
>  Kapture.2022-11-18.at.09.24.34.mp4 
> That help?

Unfortunately not. The plugin gave me the prompt to reload, but the wallpaper didn't change. The image is transparent and i'm giving it the right path.

I think I saw something about `doki.wallpaper.enable` on your main page. Might it have something to do with this?

**Comment by Unthrottled** [comment]
> I think I saw something about doki.wallpaper.enable on your main page. Might it have something to do with this?

<img width="1136" alt="Screenshot 2022-11-21 at 6 34 45 PM" src="https://user-images.githubusercontent.com/15972415/203186024-2a1964b1-d475-4624-a4b9-ca55f039bd2e.png">

That's for the `Background`. The `Background` is the image that shows up when all the tabs are closed. The `Wallpaper` is the one that shows up behind the code.

<img width="1136" alt="Screenshot 2022-11-21 at 6 36 53 PM" src="https://user-images.githubusercontent.com/15972415/203186169-5598d928-9f9f-42df-87ac-09625f521bb2.png">


The `background` for me is the Zero Two that is colored, where as the `wallpaper` is the one that's outlined & green.

Make sure you are setting the correct setting.

**Comment by zen375dragon** [comment]
I think it's working now. How did you make the explorer bar (left side) transparent, so that you can see the wallpaper behind it?

**Comment by Unthrottled** [comment]
> How did you make the explorer bar (left side) transparent, so that you can see the wallpaper behind it?

From what I remember, I made some things in the left side bar transparent so you could see the background image drawn on a panel behind it

https://github.com/doki-theme/doki-theme-vscode/pull/54

**Comment by zen375dragon** [comment]
How would I do that?

**Comment by Unthrottled** [comment]
I suppose I don't understand.

What are you asking for?

The current version of the plugin & VS code supports a background on all the parts. There isn't any gaps in coverage that I can see.

<img width="1136" alt="Screenshot 2022-11-28 at 5 46 51 PM" src="https://user-images.githubusercontent.com/15972415/204404521-ec81807c-e364-49e1-8e73-099ef15168d5.png">

VSCode Version

```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:22:48.959Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

**Comment by zen375dragon** [comment]
I think you understand what I mean.
![My project-1 (2)](https://user-images.githubusercontent.com/108360418/207185266-cd629061-b8b5-4d2e-9f09-56498d0d878d.png)

As you can see here, the Explorer tab isn't transparent. It is hiding some image behind it.

As you've said, current version of the plugin & VS code supports a background on all the parts, but it doesn't look like it's applied here.

**Comment by zen375dragon** [comment]
I think you understand what I mean.

![Screenshot (20)](https://user-images.githubusercontent.com/108360418/207189870-f954ef03-4ae3-4703-ac87-9ade0bb0d3c4.png)

As you can see, the explorer tab isn't transparent, therefore hiding some of the wallpaper behind it. Do I need to enable this feature in the VSCode setings, or extention settings?

**Comment by Unthrottled** [comment]
There is `background` & `wallpaper`.

- `background` is what you probably have set. It's what goes behind your editor. So when you have your tabs closed it shows up.
- `wallpaper` is what you want to set. It shows up in-front with the code & explorer. You'll want to use an image that is transparent so you can read text & stuff.

**Comment by zen375dragon** [comment]
<img width="1136" alt="204404521-ec81807c-e364-49e1-8e73-099ef15168d5" src="https://user-images.githubusercontent.com/108360418/208323142-597c3da0-419d-42a3-8ba5-171155e23c01.png">
Ahh, so in this screenshot, you had it set as wallpaper. I thought it was the other way round. Thanks.
