### ISSUE TITLE
How do i remove the sticker ?

### ISSUE THREAD

**Issue by Ahmad-Aiman** [doki-theme/doki-theme-vscode#186]
**Describe the bug**

**To Reproduce**

1.

**Expected Behavior**

**Environment**

**Screenshots**

**Comment by Unthrottled** [comment]
In the top menu `View` -> `Command Palette` then type in `Remove Sticker/Background`. Choose the one provided by the Doki Theme extension. You'll be prompted to restart/reload your VSCode.
