### ISSUE TITLE
Doki . sticker.css it is not responsive at all . what is soloution?

### ISSUE THREAD

**Issue by am0029** [doki-theme/doki-theme-vscode#187]
Doki sticker  it is not responsive at all . what is solution?

is it possible my css is wrong ?

in 1280 *400px vs code sticker not showing

can u share bottom right css code for responsive my custom  css is 

  "doki.sticker.css": background-position:bottom right !important;
background-position:fixed !important;
margin-top:334px !important;
background-size:360px! important;
margin-left:59px !important;
opacity:0.3 !important",

**Comment by Unthrottled** [comment]
You don't need all that extra CSS. See implementation detail [comment for an idea as to how it is rendered](https://github.com/doki-theme/doki-theme-vscode/issues/143#issuecomment-1114321010), just `z-index:100;background-position:100% 97%` should work. You can update the `background-position` to control how high or low the sticker is. The sticker panel spans the entire editor window so you can put it anywhere.
