### ISSUE TITLE
Command to display selected theme

### ISSUE THREAD

**Issue by nopeless** [doki-theme/doki-theme-vscode#188]
Can you add a command to see which theme I am using? I forget

**Comment by Unthrottled** [comment]
You can use the `Preferences: Color Theme` to figure out which color theme you are using. It shows up as the highlighted one in the list. If you installed any assets, the name of the character shows up in the bottom right hand corner of the status bar.

Is that sufficient?


https://user-images.githubusercontent.com/15972415/204000875-6e6dba27-c28b-48e4-9928-f0f736cadf9f.mp4

**Comment by nopeless** [comment]
Oh, nevermind

For the theme selection I didn't even realize that it defaulted to my selected theme


And the status bar I think I accidentally hid a long time ago? 

Anyway, thanks for the help 😅
