### ISSUE TITLE
Unable to install Hiro x Zero Two, please see active tab for more information

### ISSUE THREAD

**Issue by AryaSec1337** [doki-theme/doki-theme-vscode#194]
![image](https://user-images.githubusercontent.com/33353823/208000397-baf492e7-5eb4-4e1b-b13f-cec3e89e8e03.png)

can anyone explain how to solve it ??

**Comment by Unthrottled** [comment]
Did you try any of the suggestions presented to you?

**Comment by AryaSec1337** [comment]
I have tried according to the steps listed in the extensions profile

**Comment by Unthrottled** [comment]
So I don't know what you've installed VSCode on or how you've installed your VSCode. That's good starter information (not a mind reader).

**Comment by AryaSec1337** [comment]
I installed vscode using .deb instead of using snap , and the current location of VSCode is /usr/share/code

**Comment by Unthrottled** [comment]
Are the commands that you run to give your user ownership of the file failing? Are the files in that directory read only?

**Comment by AryaSec1337** [comment]
![image](https://user-images.githubusercontent.com/33353823/208005498-5d0bb013-f093-45a5-b47e-cc7abf05b37a.png)

okey, the problem is solved... but there is a new problem that appears below

**Comment by Unthrottled** [comment]
https://github.com/doki-theme/doki-theme-vscode#background-images

> Important!! Installing theme assets requires me to corrupt VS-Code by modifying CSS. You will have to use the "Remove Sticker/Background" command to restore VS Code back to supported status before unistalling. You can close VSCode and start it back up remove the annoying Unsupported warning. The plugin automatically fixes VSCode's checksums.

**Comment by Unthrottled** [comment]
Oh, I didn't read the message below. Let me check something real quick.

**Comment by Unthrottled** [comment]
Please provide the logs as demonstrated here
https://github.com/doki-theme/doki-theme-vscode/issues/172#issuecomment-1220510722
