### ISSUE TITLE
add my fav character please

### ISSUE THREAD

**Issue by initer3737** [doki-theme/doki-theme-vscode#195]
i love this extension because it bring happiness when i start to code , btw please add my favorite character anime like [ makima , power ,chisato,takina , kaori ] if you dont mind

**Comment by Unthrottled** [comment]
Thanks!

So you can request a theme https://github.com/doki-theme/doki-master-theme/issues 
However, I probably will be selective on the next themes I choose (if I choose anymore 88 is a bunch of themes!)

Somebody already asked for Power https://github.com/doki-theme/doki-master-theme/issues/73

Anyways, you always have custom assets, so you can make your own :) 

Going to close this issue, thanks!

**Comment by initer3737** [comment]
thanks
