### ISSUE TITLE
Spell the doki-theme name correctly,on the plugin of 'auto-theme-switch'

### ISSUE THREAD

**Issue by KylehsuXu** [doki-theme/doki-theme-vscode#198]
### my target: 
Day/night switch theme by doki-theme and auto-theme-switch**

### my problem:
I don't know how to spell the name of the doki-theme,I'm sure it's a spelling problem.

See this:
```json
    // 白天黑夜主题自动切换
    "switchConfig.darkTheme": "Doki Theme: NekoPara: Azuki",
    // can't work
    "switchConfig.lightTheme": "Doki Theme: SAO:  Asuna",

    // Vim Light Hard   can work
    // "switchConfig.lightTheme": "Vim Light Hard",

    "switchConfig.darkTime": "17:00",
    "switchConfig.lightTime": "6:00",
    "workbench.colorTheme": "Doki Theme: SAO:  Asuna"
```

**Comment by Unthrottled** [comment]
I think it might be the uuid of the theme that you have to use.

https://github.com/doki-theme/doki-theme-vscode/blob/bb4362ae1ac869b5f369169097d939e9979ed03e/buildSrc/assets/themes/nekoPara/azuki/dark/azuki.dark.vsCode.definition.json#L2

https://github.com/doki-theme/doki-theme-vscode/blob/bb4362ae1ac869b5f369169097d939e9979ed03e/buildSrc/assets/themes/swordArtOnline/asuna/light/asuna.light.vsCode.definition.json#L2

Try using those instead.

**Comment by KylehsuXu** [comment]
OK, It's solved. thank you😄
