### ISSUE TITLE
Latest doki update broke my terminal panel?

### ISSUE THREAD

**Issue by Razzlie** [doki-theme/doki-theme-vscode#199]
My terminal has odd "gaps" that weren't there the day before, the only change that has occured was doki updating.
I did not make **any** changes from yesterday to anything other than update my doki theme, including no vscode updates nor setting changes. Issue only occurs when having a doki wallpaper installed, without it there is no visual discrepancy in the terminal panel.

Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Doki Theme
v88.1.11

My terminal yesterday:
![a8452ad79a 1](https://user-images.githubusercontent.com/70892434/211598112-523d2ee6-3cb8-4b3c-b77a-d207a6cdc84d.png)
My terminal today:
![a250db006f 1](https://user-images.githubusercontent.com/70892434/211598294-38c7b98e-f500-4b82-9281-26471c3e8653.png)

As an additional odd behaviour I discovered that sometimes on reloading/rebooting VScode the terminal can look like this instead, where the horizontal "gap" is even larger, the vertical one seems to stay the same:
![3f1f9f4387 1](https://user-images.githubusercontent.com/70892434/211602792-0c9801f5-55e5-4a6a-b2a7-d959ba58d650.png)

The above goes back with either an additional reload or simply clicking, say, debug console, or any other tab in the panel, and then clicking terminal again makes it reload the terminal specifically, at which point it displays the smaller "gap" shown before.

Any help/bugfix for this issue would be appreciated. I tried searching a solution for this, but couldn't find a way to get it to look the way it did before. It appears to me like there is somehow an issue purely visually where the dark terminal layer is not covering up the entire area properly. This issue **does not** occur with any of the other tabs, only the terminal. Here is my debug console for example:
![0d74001765 1](https://user-images.githubusercontent.com/70892434/211604404-9fcfa9fa-4536-40d3-855a-736351b50736.jpg)

I also noticed that the "gap" appears when I try creating, say, a second powershell terminal on the side:
![48ace7f297 1](https://user-images.githubusercontent.com/70892434/211605196-a294cafe-1f2b-41a9-97e2-7d972bb039c1.jpg)

I also tried rolling back doki to a previous version, but it seemed to do nothing. At this point I'm not really sure what's going on with this, other than that it looks like there's some kind of visual problem; with the empty space around the terminal not having the same dark, opaque visual layer applied on top of the background, it seems?

Turning off terminal.integrated.gpu results in this:
![6f32490e46 1](https://user-images.githubusercontent.com/70892434/211619160-3d73620b-51f2-4151-8360-9edb1c91dd2b.png)

It seems GPU accel is being used to render the dark, opaque layer that should be covering the entire terminal, and somehow it isn't working quite right even when it's on, perhaps?

**Comment by Unthrottled** [comment]
That's probably just a layering issue. There is probably one or more transparent panels with the background on them that are being over-layed. Typically happens with VSCode platform updates. Might have time this weekend to look at this, otherwise might be a bit. Thanks for reporting.

**Comment by Razzlie** [comment]
Okay, good to know! Thanks for looking into this, it looks really bad with my color scheme and workspace setup, so I hope it'll be solved soon!

**Comment by Unthrottled** [comment]
@Razzlie 

Was able to replicate the issue. Will need some more time to test my changes across platforms, to make sure I didn't break anything there.

If you want you can manually install the vsix file from here https://github.com/doki-theme/doki-theme-vscode/pull/200#issuecomment-1397835861

Otherwise you'll have to wait until I get more time to test. Thanks!

**Comment by Razzlie** [comment]
Hey, thanks for the update, I'm glad you were able to replicate it and fix in your end - I gave the .vsix file a shot right away, and sadly it doesn't seem to be doing anything for me.

Here's what it says when I install it, I assume it's likely the issue has something to do with the buffer warning?
![068a22a6b61 1](https://user-images.githubusercontent.com/70892434/213676468-1f525d2e-7290-4123-8ebe-ea3e6d2fb408.png)

Here's my terminal window looking exactly the same way as before, after a reload and checking my extension is indeed v88.1.12:
![bffe352d85 1](https://user-images.githubusercontent.com/70892434/213676827-c882b297-cd72-4f83-9b59-bab56b1ac5d9.png)

**Comment by Unthrottled** [comment]
Did you re-install the wallpaper? This works by changing the VS Code CSS, so you have to run the wallpaper install command again. My bad for not including that in the instructions.

**Comment by Razzlie** [comment]
Ohh, my bad! I didn't think of that! I just tried it out, and I can verify it does indeed work now. Thank you for the assistance!

Here's how it looks now, just like it used to!

![e809a0c4cd 1](https://user-images.githubusercontent.com/70892434/213722070-e44ab246-0d15-471b-90c1-c0a9ab40b23a.png)
