### ISSUE TITLE
I dont know how to remove the wallpaper and sticker from vscode.

### ISSUE THREAD

**Issue by aaditya9899** [doki-theme/doki-theme-vscode#202]
I also messed up in the setting, pls help.

![Capture](https://user-images.githubusercontent.com/38832156/217569939-99567f44-5f64-4d9d-ab94-d5fcd3f936d6.JPG)

**Comment by Unthrottled** [comment]
While the doki theme extension in still installed. 

1. Open up the command palette https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette
2. Type in remove
3. Choose `Remove Sticker/Background`
4. Restart VSCode

https://user-images.githubusercontent.com/15972415/217690476-4131e3b7-fb61-4d21-9017-8be3d8dca969.mp4
