### ISSUE TITLE
vscode web extension support

### ISSUE THREAD

**Issue by nopeless** [doki-theme/doki-theme-vscode#203]
https://code.visualstudio.com/docs/editor/vscode-web#_extensions

Currently Doki Theme is disabled in vscode web editor (the editor you get when pressing `.` on your keyboard on a repository). I think this is a nice to have

**Comment by Unthrottled** [comment]
Looked into this, would have to probably create another build that only has the themes, because asset installation will not work on the vscode-web . Thanks for bringing it to my attention.
