### ISSUE TITLE
Unable to remove unsupported status using supplied help

### ISSUE THREAD

**Issue by kynetical** [doki-theme/doki-theme-vscode#204]
**Describe the bug**
Using the commands in code I was unable to remove the unsupported status automatically. I followed the commands given through the automatically appearing help, but this was not sufficient to resolve the issue. 

**To Reproduce**
1. Install vscode through .deb
2. Add any doki-themes
3. Receive error about inability to remove unsupported status
4. Use command to grant ownership of product.json
5. Restart VS-Code
6. Attempt command again
7. Receive failure still

**Expected Behavior**
Command to work after following help page advice

**Environment**
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.11-76060111-generic
Sandboxed: No

Please also include the Doki-Theme version
Doki Theme
v88.1.13

**Comment by kynetical** [comment]
- I was able to resolve this issue by granting myself ownership of the entire code dir in /usr/share/

- Granting ownership of product.json was not sufficient.

- I did confirm the command to take ownership of product.json worked, and I did have ownership of the file. The commands inside code were still failing.

![image](https://user-images.githubusercontent.com/66834451/220929123-dcb811dd-e853-4255-a012-d831c2828b58.png)


This is on Pop!_Os 22.04 LTS

**Comment by Unthrottled** [comment]
Hmm, that is curious. Thanks for providing this information.

Please provide the logs as demonstrated here after running asset installation.
https://github.com/doki-theme/doki-theme-vscode/issues/172#issuecomment-1220510722

**Comment by kynetical** [comment]
- It appears that because it is trying to rename `product.json`, versus edit it, it needs write perms to the parent folder. Giving myself ownership of the `/usr/share/code/resources/app` directory (in addition to ownership of `product.json`) is enough to allow it to work correctly.

![image](https://user-images.githubusercontent.com/66834451/221066301-ff47e28c-cb88-4ff5-b43a-0dbb450c9ea2.png)

```ts
[Extension Host] Fetching resource checksum: https://doki.assets.unthrottled.io/stickers/vscode/yuruCamp/rin/dark/shima_rin_dark.png.checksum.txt
console.ts:137 [Extension Host] Fetching resource checksum: https://doki.assets.unthrottled.io/backgrounds/wallpapers/transparent/shima_rin_dark.png.checksum.txt
console.ts:137 [Extension Host] Fetching resource checksum: https://doki.assets.unthrottled.io/backgrounds/wallpapers/shima_rin_dark.png.checksum.txt
notificationsAlerts.ts:42 Unable to remove [Unsupported] status!
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
addNotification @ notifications.ts:204
notify @ notificationService.ts:175
(anonymous) @ mainThreadMessageService.ts:77
d @ mainThreadMessageService.ts:42
$showMessage @ mainThreadMessageService.ts:36
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
fire @ ipc.net.ts:671
Z.onmessage @ localProcessExtensionHost.ts:615
log.ts:404   ERR [Extension Host] Error: EACCES: permission denied, rename '/usr/share/code/resources/app/product.json' -> '/usr/share/code/resources/app/product.json.orig.1.75.1'
	at Object.renameSync (node:fs:980:3)
	at exports.fixCheckSums (/home/ron/.vscode/extensions/unthrottled.doki-theme-88.1.13/out/CheckSumService.js:32:34)
	at /home/ron/.vscode/extensions/unthrottled.doki-theme-88.1.13/out/ThemeManager.js:170:35
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
console.ts:137 [Extension Host] Error: EACCES: permission denied, rename '/usr/share/code/resources/app/product.json' -> '/usr/share/code/resources/app/product.json.orig.1.75.1'
	at Object.renameSync (node:fs:980:3)
	at exports.fixCheckSums (/home/ron/.vscode/extensions/unthrottled.doki-theme-88.1.13/out/CheckSumService.js:32:34)
	at /home/ron/.vscode/extensions/unthrottled.doki-theme-88.1.13/out/ThemeManager.js:170:35
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
fire @ ipc.net.ts:671
Z.onmessage @ localProcessExtensionHost.ts:615
```

**Comment by Unthrottled** [comment]
Got it, thanks! I'll add some stuff to the help message that includes information about needed to make a copy of the original product file.

**Comment by kynetical** [comment]
Just for validation, I also tested this on a fresh install of Fedora 37 and found the same results.
