### ISSUE TITLE
Installing customs backgrounds 

### ISSUE THREAD

**Issue by Sorey732** [doki-theme/doki-theme-vscode#207]
Hi, can you explain clearly how to setup custom background? I don't understant with the short guide already present ^^'
Can I do this in VS code directly ? or I have to go in some files?

**Comment by Unthrottled** [comment]
https://user-images.githubusercontent.com/15972415/222602172-0c2d675e-aab6-474c-b59f-1d2897c6f943.mp4


Here's a video. The process is the same if you are on windows. Just find the file you want. Get the path. Put it in the setting. Reload. ???. Profit!
