### ISSUE TITLE
Custom themes with theme cycle rotation

### ISSUE THREAD

**Issue by Ayifee** [doki-theme/doki-theme-vscode#208]
**Is your feature request related to a problem? Please describe.**

Hello could i make it so that i can add wallpapers to the list, and using another application it cycles threw the themes, currently i know you can add custom ones but you can only have 1
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by justalemon** [comment]
Like the [Jetbrains Theme Randomizer](https://github.com/Unthrottled/theme-randomizer)? Also made by @Unthrottled, it allows you to select a set of themes to be in constant rotation.

**Comment by Unthrottled** [comment]
I'm not going to support that feature in this plugin.

You could https://github.com/shalldie/vscode-background instead, but it doesn't look like it cycles full screen images though.

Thanks!

**Comment by Unthrottled** [comment]
@justalemon They are probably referring to https://github.com/buchizo/ClaudiaIDE
