### ISSUE TITLE
How to apply the custom stickers?

### ISSUE THREAD

**Issue by ColderCof** [doki-theme/doki-theme-vscode#212]
I've added the path to my sticker in the setting.json under the sitcker:path
![image](https://user-images.githubusercontent.com/129467165/228995678-dcec14a5-2ea8-4480-89be-44c0d16e1df1.png)
Is there something else I'm supposed to do after doing so? Cause I don't quite find it in the read.me page. Neither do I find commands that does installing customized stickers or what not.
Tell me if I'm being blind or stupid or something.
Thanks.

**Comment by Unthrottled** [comment]
You might need to reload afterwards (provided your path is correct).

Here is a video https://github.com/doki-theme/doki-theme-vscode/issues/207#issuecomment-1452771862

Let me know if you need any thing else.

**Comment by ColderCof** [comment]
Got it working! Turns out it won't work in the Picture folder. Thanks!
