### ISSUE TITLE
Integrated Terminal Text does not appear on Custom Wallpapers

### ISSUE THREAD

**Issue by VincentRPS** [doki-theme/doki-theme-vscode#213]
**Describe the bug**
When using a custom wallpaper on VSCode, the integrated terminal's text does not appear.
This seemingly does exclude special characters though?

I have tried other themes with different contrasts and coloring, but they still
lead to this error so I doubt it's a background saturation flaw.

**To Reproduce**

1. Use a Custom Wallpaper
2. Open the Terminal

**Expected Behavior**
The integrated terminal's text appears

**Environment**

Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
Doki-Theme: v88.1.15

**Screenshots**

![image](https://user-images.githubusercontent.com/82736662/230255470-d4d39b87-41a6-4a73-b082-98d2f64c874b.png)
![image](https://user-images.githubusercontent.com/82736662/230256074-21fb164c-4eb6-4f92-988a-75bac601761f.png)
![image](https://user-images.githubusercontent.com/82736662/230256178-26015873-996f-4f9a-aa94-e8f9d69779b1.png)

The expected result is for it to display something similar to the following:

![image](https://user-images.githubusercontent.com/82736662/230256526-defd1d24-837b-45a8-93c5-ab460d78ce70.png)

**Comment by Unthrottled** [comment]
You need to make your custom asset partially transparent
https://github.com/doki-theme/doki-theme-vscode/issues/178

It was also shown that you cannot see the terminal in the custom assets part of the documentation. https://github.com/doki-theme/doki-theme-vscode#custom-assets
