### ISSUE TITLE
Change the wallpaper and stick after an time.

### ISSUE THREAD

**Issue by pedrobbarbosa** [doki-theme/doki-theme-vscode#215]
I think it should be a good configuration option that the plugin should change the background image and the stick after some time.
I want to configure that the wallpaper and the sticker should change after 1hour or every time vscode open.

**Comment by Unthrottled** [comment]
That would be nice. I think that this falls under the category of #117 though, so I'll close this and track it from there.

**Comment by pedrobbarbosa** [comment]
But are you going to do it?
