### ISSUE TITLE
Network conection

### ISSUE THREAD

**Issue by dominhdang148** [doki-theme/doki-theme-vscode#216]
So, I tried to install some new wallpapers. After a while, it show this notification
![image](https://user-images.githubusercontent.com/80236955/235884377-4d73d69a-42ef-4681-be8f-f71ad6067ebb.png)
I know it must be my connection problem. However, my connection is still normal that I can still post this issue here. 
I also tried to reinstall Doki theme, run Restore asset command, restart my computer, but it isn't work. 
What should I do?

**Comment by Unthrottled** [comment]
Few questions:

- What kind of VSCode are you using? Is it the desktop version, the browser version (code server) or something else?
- Are you able to see the image using this link? https://doki.assets.unthrottled.io/backgrounds/wallpapers/emilia_light.png

What it should look like (but please follow the link)

![Emilia](https://doki.assets.unthrottled.io/backgrounds/wallpapers/emilia_light.png)

**Comment by dominhdang148** [comment]
> Few questions:
> 
> * What kind of VSCode are you using? Is it the desktop version, the browser version (code server) or something else?
> * Are you able to see the image using this link? https://doki.assets.unthrottled.io/backgrounds/wallpapers/emilia_light.png
> 
> What it should look like (but please follow the link)
> 
> ![Emilia](https://camo.githubusercontent.com/10404f7c5ee062392102bdf27c54597d3008931d7da9fd08125e2ec5230ebcab/68747470733a2f2f646f6b692e6173736574732e756e7468726f74746c65642e696f2f6261636b67726f756e64732f77616c6c7061706572732f656d696c69615f6c696768742e706e67)

I am using VSCode Desktop version
I followed the link on my browser and it still appear
![image](https://user-images.githubusercontent.com/80236955/235924500-4fe7cfa7-bf1b-4826-915a-c9b40b5f017d.png)

**Comment by dominhdang148** [comment]
Ohh thanks, It work again. I tried in hopeless and decided to turn off the computer and go to sleep :D. Then, this morning, I turn on the computer and try again, and it work. I still don't know how it was solved
