### ISSUE TITLE
background is not resetted.

### ISSUE THREAD

**Issue by jomin398** [doki-theme/doki-theme-vscode#221]
**Describe the bug**
background is not resetted when it's uninstalled. 

**To Reproduce**
1. install theme
2. set background image. (miku etc....)
3. uninstall.

**Expected Behavior**
resetted background.

**Environment**
OS (Windows)
Published
3/30/2020, 20:10:28
Last released
2/27/2023, 06:05:05
Last updated
6/6/2023, 21:54:43
Identifier
unthrottled.doki-theme

**Comment by justalemon** [comment]
When enabling the wallpaper, it says that the wallpaper will remain after removing the plugin.

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/fcb58ff8-1f08-4c92-9465-0548f0a545b2)

You will also get a notification after closing the Settings window.

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/112ee9c0-6822-44d5-9c04-35be7e38cbf4)

If you want to remove the wallpaper manually after uninstalling The Doki Themes, go to `Appearance & Behavior > Appearance > Background image... > Clear and Close`.

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/fef8ac03-8026-40f2-aae9-e9142c045019)

**Comment by jomin398** [comment]
i see. thanks!
