### ISSUE TITLE
Terminal tab background is broken since the latest VSC update (1.82.0)

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [doki-theme/doki-theme-vscode#233]
**Describe the bug**
After updating to the latest Visual Studio Code update (1.82.0), when you reapply the background, the terminal tab doesn't have the background set, however the rest of the tabs have the background. This issue still appears even when I unset my custom background.

**To Reproduce**
1. Ensure you are on the latest version (atleast 1.82.0)
2. Set the background for your Visual Studio Code

**Expected Behavior**
All views should have the background set correctly, like before the update

**Environment**
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.23536
Doki theme version: v88.1.15

**Screenshots**
![image](https://github.com/doki-theme/doki-theme-vscode/assets/30568955/6012671f-55a3-4f3b-95b4-841971cd8577)
![image](https://github.com/doki-theme/doki-theme-vscode/assets/30568955/e9a81b5f-59d4-41db-ac88-3dbca7bc50ee)

**Comment by WingXSaber** [comment]
Same issue here for a while now. I'm considering downgrading my VSCode just for it.

**Enviornment:**
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479fleb312d
Date: 2023-09-14T05:51:20.9812 (3 wks ago)
Electron: 25.8.1
ElectronBuildid: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
ve: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-84-generic

**Comment by justalemon** [comment]
Same problem here, but in 1.18.0 instead.

Version: 1.84.0-insider (user setup)
Commit: 4678919d52909efc7c4ab958a2e5c8f45d50ffc3
Date: 2023-10-13T05:34:13.175Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
