### ISSUE TITLE
How to change/custom character's name in bottom right corner?

### ISSUE THREAD

**Issue by d4xwrld** [doki-theme/doki-theme-vscode#238]
Does it possible to change it?, if it can, how/which file that i need to modified?

**Comment by justalemon** [comment]
You can either select an existing sticker:

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/5b5a292d-dc6b-43a0-b842-4a6fd026214e)

Or set a custom file path in the configuration:

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/fd69a403-dbd8-4452-b42c-2ffd2af9d92e)

**Comment by d4xwrld** [comment]
ofc, i mean this thing on status bar.
![image](https://github.com/doki-theme/doki-theme-vscode/assets/83622225/5928c215-3328-4259-b8c4-917a1ee69d1e)

the configuration said this
![image](https://github.com/doki-theme/doki-theme-vscode/assets/83622225/4768961b-4cfd-4e69-9f0d-08bc8588130e)

Mybe there someone that alr changed it and know the steps.

**Comment by justalemon** [comment]
I have said option:

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/0400d4d5-5303-4fb6-9930-7c25e43adb6f)

![image](https://github.com/doki-theme/doki-theme-vscode/assets/11861253/bb15d774-e9e8-42ea-8a27-6c070f8c7519)

**Comment by d4xwrld** [comment]
thanks for your answer, that helped me a lot!
