### ISSUE TITLE
How can I change opacity of existing wallpaper?

### ISSUE THREAD

**Issue by happy-1201** [doki-theme/doki-theme-vscode#251]
I'm new to this community, not sure if this is the right way to ask questions so if I am being a jerk, please forgive.

I really like the konata second wallpaper, but wanna apply it in zero two obsidian theme which makes the wallpaper shown way too dim

I've been looking through extensions for while, found opacity setting for stickers in web-extension.bundled.js, but couldn't find the opacity setting for wallpaper.
Does anyone know where to change opacity for wallpaper?

**Comment by Unthrottled** [comment]
Here is a comment on how to change the opacity
https://github.com/doki-theme/doki-theme-vscode/issues/150#issuecomment-1140349756

Here is the Konata second wallpaper

![Kontana](https://doki.assets.unthrottled.io/backgrounds/wallpapers/konata_dark_secondary.png)

**Comment by happy-1201** [comment]
Oh, thank you for quick response.
Never knew I could set opacity to image itself.

by the way, thank you for making this extension. I really love it
