### ISSUE TITLE
[Just a question] Where are the stickers stored?

### ISSUE THREAD

**Issue by AlwaysBorderRadius** [doki-theme/doki-theme-vscode#256]
I use a 4k display so some of the stickers look really blurry and I wanted to upscale them.

**Comment by Unthrottled** [comment]
You can use custom assets
https://github.com/doki-theme/doki-theme-vscode?tab=readme-ov-file#custom-assets

**Comment by AlwaysBorderRadius** [comment]
Yes, I know. But the problem is that I want to use one of the included stickers (the Zero Two Dark Obsidian one). 
I tried to search for it on the Internet, but I couldn't find it. 
That's why I'm asking, where is the sticker that the extension uses, so I can take it and upscale it.

**Comment by Unthrottled** [comment]
Here is the larger one I made which I downscaled into the sticker.

![zero_two_obsidian_sticker](https://github.com/user-attachments/assets/c02eded6-5778-40e3-a97d-633c448e0e1a)

**Comment by AlwaysBorderRadius** [comment]
niceeee, now it's perfect. Thanks
