### ISSUE TITLE
Can't apply wallpapers anymore

### ISSUE THREAD

**Issue by quincynyan** [doki-theme/doki-theme-vscode#257]
Yes I have checked the FAQs. 

**Describe the bug**

This
![image](https://github.com/user-attachments/assets/d7bd467d-5f54-4d84-9288-dbcf1ccffc40)
![image](https://github.com/user-attachments/assets/9554669c-fa6c-46f7-be6a-d342b6e02c7e)
![image](https://github.com/user-attachments/assets/1c1e2436-13a9-4c56-9836-076401251ef2)

But colors work

![image](https://github.com/user-attachments/assets/8f87087c-b944-47dd-9596-bcebc3f996f3)

Got the latest version
![image](https://github.com/user-attachments/assets/5256e92e-9700-4567-8d88-19e69a1e140b)

**To Reproduce**

1. Urr apply themes I guess?

**Expected Behavior**

It should be working

**Environment**
 v88.1.17

**Screenshots**

**Comment by quincynyan** [comment]
Also this
![image](https://github.com/user-attachments/assets/8d463e73-3957-4eb9-8650-9c21d38f3d52)
![image](https://github.com/user-attachments/assets/b5f9f3ea-43a5-41bd-a037-a10637338ab3)


I have already tried uninstalling and reinstalling the theme.

**Comment by quincynyan** [comment]
![image](https://github.com/user-attachments/assets/f254be64-5ff3-4824-8b49-1d50def3f186)

**Comment by StaraaX** [comment]
still no solution ? :/

**Comment by root9464** [comment]
> still no solution ? :/

yep (

**Comment by Unthrottled** [comment]
Hey! Thanks for reporting, will take some time later this week to look into the issue.

**Comment by root9464** [comment]
> Hey! Thanks for reporting, will take some time later this week to look into the issue. 

I will be very grateful if you solve this problem. 🙏

**Comment by lau-luna** [comment]
![image](https://github.com/user-attachments/assets/091a66a6-430f-4ae5-8327-4290f27506cd)
I have the same issue. And it happens with the stickers too.

**Comment by shivanshsharma8834** [comment]
Having the same issue here as well. 
![Screenshot 2024-10-04 051937](https://github.com/user-attachments/assets/72039dba-e2f2-4ece-a3af-190be7daf6ea)

**Comment by StingrayVa11** [comment]
same here, the only thing working for me so far is the custom colours. 
![image](https://github.com/user-attachments/assets/ef12051b-93e2-4dba-b788-20707962e9ef)

**Comment by DasxGz** [comment]
Same 😭 
![imagen_2024-10-03_230903784](https://github.com/user-attachments/assets/c209198c-c4af-45bb-add1-c450d742fa94)

**Comment by theanimatorspal** [comment]
Same 😭😭
![image](https://github.com/user-attachments/assets/3c203448-e5d8-4c2f-8d59-3c3e5f60da84)

**Comment by cBinimelis** [comment]
Same issue here. Stickers and wallpapers aren't working, only theme-colors, this only happened after I updated VS Code.
![image](https://github.com/user-attachments/assets/ab3b04fa-0252-4bb8-aca8-9982823fdaee)

**Comment by Marchello0509** [comment]
Am I the only one with this problem with VS code 1.94.0?
![image](https://github.com/user-attachments/assets/5ce56628-a08e-4d22-9919-c0f17ed0060c)

**Comment by Unthrottled** [comment]
![Attention](https://media1.tenor.com/m/W8wGkjWe1ikAAAAC/scream-attention.gif)

Attention!!!

I am aware of what’s causing issue I just need time to fix it. I am moving and I have a newborn, please be patient.

**Comment by Marchello0509** [comment]
> ![Attention](https://camo.githubusercontent.com/49c35e413ab2500ecc5f5f3f802a40fe109af69605c8c87c1f184fb72e24d461/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f573877476b6a576531696b41414141432f73637265616d2d617474656e74696f6e2e676966) [ ![Attention](https://camo.githubusercontent.com/49c35e413ab2500ecc5f5f3f802a40fe109af69605c8c87c1f184fb72e24d461/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f573877476b6a576531696b41414141432f73637265616d2d617474656e74696f6e2e676966) ](https://camo.githubusercontent.com/49c35e413ab2500ecc5f5f3f802a40fe109af69605c8c87c1f184fb72e24d461/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f573877476b6a576531696b41414141432f73637265616d2d617474656e74696f6e2e676966) [ ](https://camo.githubusercontent.com/49c35e413ab2500ecc5f5f3f802a40fe109af69605c8c87c1f184fb72e24d461/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f573877476b6a576531696b41414141432f73637265616d2d617474656e74696f6e2e676966)
> 
> Attention!!!
> 
> I am aware of what’s causing issue I just need time to fix it. I am moving and I have a newborn, please be patient.

Okay, good luck!

**Comment by Marchello0509** [comment]
> I am aware of what’s causing issue I just need time to fix it. I am moving and I have a newborn, please be patient.
Okay, good luck!

**Comment by shivanshsharma8834** [comment]
No problem, take your time.
I'm also trying to find the issue and fix it.

**Comment by LHETHA** [comment]
I was also wondering why this error suddenly occurred. Take the time you need to fix the issue - I don't mind waiting. And thanks a lot for creating the extension.

**Comment by Marchello0509** [comment]
The mistake is not the most important thing, the main thing is that everything goes according to your plans. Good luck!

**Comment by LHETHA** [comment]
I'd like to add that @cBinimelis' solution by downgrading to VS Code 1.93.1 has worked for me, too. Doki's now functioning just like before the error occured. I have the version `v88.1.17` installed. Wallpapers and stickers are now applicable again.

Also, I had a look at the Developer Tools' console and the following errors were logged each time I've run Doki's commands (as the only extension installed) when it used to throw the above-shown errors:
`ERR [network] #31: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Canceled`
`Activating extension 'unthrottled.doki-theme' failed: ENOENT: no such file or directory, scandir 'C:\mnt\c\Users'.
$onExtensionActivationError @ mainThreadExtensionService.ts:107`

I hope this helps.

**Comment by isaaaaachr** [comment]
Same problem here. Take your time man:)

**Comment by jailsonmartinsfilho** [comment]
i did vscode downgrade but not work

**Comment by Unthrottled** [comment]
![FIxed](https://media1.tenor.com/m/TrlCOvj8uMcAAAAd/nice-bakuretsu.gif)

I have the fix published. 

They changed how the plugin is loaded and the `require` no longer worked (which is what is used to determin where the assets are installed).

I verified it works on my machine. Thank you everybody.

**Comment by ntytov** [comment]
THANK YOU, EVERYTHING WORKED!!!@Unthrottled

**Comment by jailsonmartinsfilho** [comment]
thank u Unthrottled-senpai

**Comment by root9464** [comment]
@Unthrottled THANSK !!!!!!!!

**Comment by shivanshsharma8834** [comment]
Thank you very much @Unthrottled
