### ISSUE TITLE
Command not found doki-theme

### ISSUE THREAD

**Issue by root9464** [doki-theme/doki-theme-vscode#258]
I use vs code insiders and doki-theme, previously when I used windows everything worked fine, but now I'm sitting on linux arch and I get an error when I want to install wallpaper

> comand doki-theme.theme.wallpaper.Coconut not found

**Comment by quincynyan** [comment]
Same issue as #257

**Comment by root9464** [comment]
> Same issue as #257

waiting for answers))

**Comment by AxelTav001** [comment]
Same issue as #257

**Comment by DasxGz** [comment]
![image](https://github.com/user-attachments/assets/2f33701e-dbaa-4129-935c-633a1dc43ac8)
like this?

**Comment by r0hitm** [comment]
Experience this myself. Everything worked fine before, now after doing an update it broke, I've tried reinstalling the extension, the vscode. Didn't work.

@DasxGz yup, that's what I get

**Comment by AlessandroAT** [comment]
still no fix?

**Comment by LaNNy-kz** [comment]
Ye still no fix(( 
![Снимок экрана 2024-10-05 140919](https://github.com/user-attachments/assets/4fe3d0f7-ff69-49db-805e-d2906badf869)

**Comment by dino65-dev** [comment]
same issue , any solution yet?

**Comment by ZEROMATOI** [comment]
when it is fixed let me know :")

**Comment by Sohan-o7p** [comment]
Same issue here as #257 Please fix this man

**Comment by Unthrottled** [comment]
![Thumbs Up](https://media1.tenor.com/m/TrlCOvj8uMcAAAAd/nice-bakuretsu.gif)

Published the fixed version, I verified it worked on my machine.

**Comment by ZEROMATOI** [comment]
thanks:3

**Comment by AxelTav001** [comment]
thanks 🫶
