### ISSUE TITLE
Regarding not supported files

### ISSUE THREAD

**Issue by RahulARanger** [doki-theme/doki-theme-vscode#26]
**Describe the bug**

I have been using Doki theme in both vs code and vs code insiders in Windows.
It seems vscode recognizes Doki theme extension files are not supported.
They seem to work fine. But just that message appears.
I have even attached the snapshot.

Problems faced:
 
 * Whenever I open vscode, this pop-up message appears.

Actually I tried to make sure whether that pop up appears over this extension or not by reinstalling vscode and this extension. And I found it appears whenever I download some stickers from this extension (like rem).
Honestly, it's the best feature that I really appreciate.
I would be really happy.

As far I can say I face no other issues other than that pop-up

**Expected Behavior**

I expect vscode to recognize Doki theme as uncorrupt files.

**Environment**
* Windows
* Linux
Doki-Theme version: v5.0.0

**Screenshots**
![problrm](https://user-images.githubusercontent.com/57987728/90622722-24fd2200-e233-11ea-95ed-0235fa4c9a1b.PNG)

**Comment by Unthrottled** [comment]
Thank you for spending time making a high quality issue, I appreciate the details!

So installing the stickers requires the plugin to change internal VS Code css. It can't do it any other way. I think you were also prompted, before you installed your first sticker, that your VSCode will be corrupted if you chose to continue.

I've noticed on my Windows 10 machine that I can't click on the gear that says `Don't show this again`.

If you want, you can give this fix a try:
https://github.com/be5invis/vscode-custom-css/issues/15#issuecomment-408693784

**Comment by RahulARanger** [comment]
Thanks for providing the Solution and also for responding.

https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums 
This extension suppressed that pop-up.
I understand that vs-code doesn't allow any changes in its CSS.

Please continue to add more themes and stickers in vscode too.
