### ISSUE TITLE
Warning message after installing the stickers.

### ISSUE THREAD

**Issue by Gianni-Lab** [doki-theme/doki-theme-vscode#27]
After installing the stickers every time I open or reload vscode appears this message: `Your Code installation appears to be corrupt. Please reinstall.`, I haven't noticed any other problem besides the warning. If I remove the stickers, the warning doesn't appear again.

**Comment by Unthrottled** [comment]
Hey!

Unfortunately, this is a known issue. VSCode does not support CSS customization without corruption. [Please see this github comment for the reason](https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312)

However, there is a workaround, you can follow this thread here:
https://github.com/doki-theme/doki-theme-vscode/issues/26#issuecomment-676180921

Let me know if you have any more issues.

**Comment by Unthrottled** [comment]
Where you prompted with this the first time you installed stickers?

![image](https://user-images.githubusercontent.com/15972415/93272629-86a1a500-f77b-11ea-8f6b-50b0443f9949.png)

Is there anything else that I could have done to help you be aware of this issue? Added a FAQ, README entry, or something?

**Comment by AryaSec1337** [comment]
![image](https://user-images.githubusercontent.com/33353823/207999788-d864d4b2-9af5-4d52-97b1-6d9487a7db02.png)

can anyone explain how to solve it ??
