### ISSUE TITLE
Support for VS Code version 1.52.0

### ISSUE THREAD

**Issue by RahulARanger** [doki-theme/doki-theme-vscode#30]
**Describe the bug**

Actually, when I upgraded my vscode Insiders from 1.51.0 to 1.52.0, The Sticker at the bottom right corner disappeared but the main one (at the mid) is still visible.

That sticker (Bottom-Right Corner ones) opens regardless of whichever active window. I really love that feature. Thank You For that. I would be grateful if you look into this issue.

**Expected Behavior**

* sticker which was visible at the bottom right corner should be visible.

* I guess this has something to do with the version of the Vscode. It was working fine in version  Vscode 1.51.0

**Environment**

* Windows
* VS Code Insiders  1.52.0
* Doki Version v7.0.0 

**Screenshots**
* Was Working in vs code 1.51.0 

![valid](https://user-images.githubusercontent.com/57987728/98433180-9fc73200-20ea-11eb-8637-1eb23e4f409b.PNG)

* Not Visible in vscode 1.52.0
![problem](https://user-images.githubusercontent.com/57987728/98433181-a2298c00-20ea-11eb-83b1-08da850dd040.PNG)

**Some More Details**

* It was working fine in Vscode 1.51.0 even it was vscode insiders.
* VS code (user) didn't receive 1.52.0 yet.
* I have used same Doki Theme (version 7.0.0) for both vscode(Users) and Vscode(insiders).
* This is not just for REM Stickers but also for others. I would provide even more screenshots if needed.

**Comment by Unthrottled** [comment]
Hello friend! Thank you for bringing this to my attention. I'll adopt the VSCode insiders as well, so that I can catch these issues as well :)

I tested it and made sure that it worked on my Linux machine. However, I did not test on my Windows machine. If it is not fixed there, please re-open this issue :bow: 

The `v7.0.1` is now public.

**Comment by RahulARanger** [comment]
@Unthrottled 
wow, that was so quick!
 Thank You so much, friend! UwU

It's working fine in Windows.
