### ISSUE TITLE
[Ubuntu 20.04] Stickers install error

### ISSUE THREAD

**Issue by Comet-Z** [doki-theme/doki-theme-vscode#34]
I'm using Ubuntu 20.04 and tried to install a sticker, however it gave me an error. I entered a command that was in the _Doki Sticker Help_ file which is `sudo chown -R $(whoami) /snap/code/50/usr/share/code/resources/app/out/vs/workbench` but the error is still there. Tried to reopen VS Code, still nothing

Terminal output after running the command: 
`chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/back-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/forward-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/letterpress-dark.svg': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/letterpress-hc.svg': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/letterpress.svg': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser/parts': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/browser': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/continue-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/continue-without-debugging-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/pause-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/restart-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stepinto-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stepout-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stepover-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stop-tb.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/node/telemetryApp.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/node/telemetryApp.nls.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug/node': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/debug': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser/media/language-icon.svg': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser/media/theme-icon.png': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser/media': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/extensions': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal/node/TerminalHelper.scpt': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal/node/iTermHelper.scpt': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal/node': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/notebook/common/services/notebookSimpleWorker.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/notebook/common/services': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/notebook/common': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/notebook': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/output/common/outputLinkComputer.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/output/common': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/output': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/fake.html': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/host.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/index.html': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/main.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/service-worker.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre/electron-index.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre/index.html': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/webview': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser/media/commandpalette-dark.svg': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser/media/commandpalette.svg': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser/media': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib/welcome': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/contrib': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.nls.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.nls.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/httpsWebWorkerExtensionHostIframe.html': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/search/node/searchApp.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/search/node/searchApp.nls.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/search/node': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/search': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.nls.js': Read-only file system
chown: changing ownership of '/snap/code/50/usr/share/code/resources/app/out/vs/workbench': Read-only file system
`

Any thoughts on this one?

**Comment by Unthrottled** [comment]
Hey Friend!

So I ran into this same problem on my Ubuntu 20.20, I installed it via `snap`. 

Turns out that the `/snap/` directory is mounted as a read-only partition. So instead of figuring out how to make it write-able, I just uninstalled it from snap and used [the apt installation](https://linuxize.com/post/how-to-install-visual-studio-code-on-ubuntu-20-04/#installing-visual-studio-code-with-apt)

You'll need to run `sudo chown -R $(whoami) /usr/share/code/resources/app/out/vs/workbench ` every after every VSCode update. 

Darn you VSCode for not allowing CSS additions! [See this comment for more info](https://github.com/doki-theme/doki-theme-vscode/issues/27#issuecomment-693018863)

I could add something about `snap` and Ubuntu in the help if you figure something out.

**Comment by Comet-Z** [comment]
Thank you, that worked. Love your theme!

**Comment by D3rJust1n** [comment]
![image_2023-04-09_173718227](https://user-images.githubusercontent.com/116668649/230782233-9c4a5b67-2c17-4a41-87f7-208ef66fcbef.png)
Ich nutze die Erweiterung in VSC auf Ubuntu 22.04
Ich bekomme diese Meldung nciht weg, kann ich dagegen etwas tun?

**Comment by mo3stx8** [comment]
what about the installed extentions will they will be restored after installing VS code from apt?
