### ISSUE TITLE
Makise Kurisu Skin

### ISSUE THREAD

**Issue by h80r** [doki-theme/doki-theme-vscode#37]
I stumbled across this theme and liked it a lot, but it doesn't have my waifu, so I'm prevented by law from using it!
I think Makise Kurisu would make a great addition to this theme, is it a reasonable request?

**Comment by Unthrottled** [comment]
:thinking: Hmm, I think that is do-able.

She was in the line up for the last batch of Waifu to be released, so maybe she'll make it in this round. I'm currently searching for one more top tier waifu, then I think I'll be ready to work on the batch.

If she does make the cut, it will probably be out sometime near christmas. My gift to the community :gift: 

You'll be able to track the status here https://github.com/doki-theme/doki-master-theme/issues/30

**Comment by sanidhyajain1** [comment]
can you add some boys too?

**Comment by Unthrottled** [comment]
@sanidhyajain1 :thinking: I don't know if it appropriate/on-brand. I'm not completely opposed to the idea. It's just other plugins (on other platforms such as [Intellij](https://github.com/doki-theme/doki-theme-jetbrains)) follow a cutesy/moe/feminine look and feel. 

![image](https://user-images.githubusercontent.com/15972415/101151459-4bc74480-35e7-11eb-9a60-c3917f60f614.png)

I'd have to consider the implications/branding across platforms of adding male-based themes as well.

Long answer short, _maybe_.

**side note**

I'm more inclined to choose this:

![Astolfo](https://vignette.wikia.nocookie.net/fateanother/images/b/b8/RiderAstolfoStage2.jpg/revision/latest/top-crop/width/360/height/450?cb=20190708225924)

over this:

![Guts Beserk](https://static.wikia.nocookie.net/berserk/images/4/40/Manga_V38_Guts.png/revision/latest/top-crop/width/360/height/360?cb=20170919104357)

As Astolfo is more on brand than Guts (less work for me to consider :)

**Comment by sanidhyajain1** [comment]
i was talking about cute boys XD
![saikik](https://user-images.githubusercontent.com/59452778/101154589-ef4a4080-364b-11eb-803c-f40ed3b93797.png)

**Comment by Unthrottled** [comment]
@sanidhyajain1 I see, glad we are on the same page :smiley: 

Your are more than welcome to [submit a theme request](https://github.com/doki-theme/doki-master-theme/issues/new?assignees=&labels=&template=theme_request.md&title=%5BTheme+Request%5D+). I've already have a backlog, but you can take advantage of [vscode-background](https://marketplace.visualstudio.com/items?itemName=shalldie.background) to get you what you want regardless of my decisions.

**Comment by sanidhyajain1** [comment]
nom nom

**Comment by Unthrottled** [comment]
@h80r 
Thank you for the theme suggestion. 

![Screenshot from 2020-12-29 05-48-13](https://user-images.githubusercontent.com/15972415/103283089-41f1f080-499d-11eb-8f9d-768018943975.png)

I think it turned out okay :smiley:. I may make small tweaks later on, but this is what we got!

I'll have to add Steins Gate to my ever growing list of anime to watch :v:
