### ISSUE TITLE
2 questions.

### ISSUE THREAD

**Issue by ehAsuna** [doki-theme/doki-theme-vscode#38]
1. How do I see the stickers?...I can see the color theme but am confused on what to do.
2. Is Asuna~Dark mode a possibility?

**Comment by Unthrottled** [comment]
@ehAsuna Sorry for not responding (but I did track you request)! Adding Asuna Dark was a good idea. The next release will contain Asuna's dark mode.

For future reference, you can submit a theme request [here](https://github.com/doki-theme/doki-master-theme/issues).
