### ISSUE TITLE
Corrupt Instalation

### ISSUE THREAD

**Issue by Neonairb** [doki-theme/doki-theme-vscode#40]
I don´t know why but after download the sticker always that I refresh VS appears the message "Your Code installation appears to be corrupt. Please reinstall.", and continue appearing after uninstall the theme

**Comment by Unthrottled** [comment]
>  uninstall the theme

Did you run the `Doki-Theme: Remove Sticker/Background` to remove the stickers?

**Comment by Neonairb** [comment]
I did and the message stops appearing, but as soon as I reinstall a stiker it comes back.

**Comment by Unthrottled** [comment]
Unfortunately, this is a known issue. VSCode does not support CSS customization without corruption. [Please see this github comment for the reason](https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312)

However, there is a workaround to removing the warning, you can follow this thread here:
https://github.com/doki-theme/doki-theme-vscode/issues/26#issuecomment-676180921

**Comment by Unthrottled** [comment]
Where you prompted with this the first time you installed stickers?

![image](https://user-images.githubusercontent.com/15972415/93272629-86a1a500-f77b-11ea-8f6b-50b0443f9949.png)

Is there anything else that I could have done to help you be aware of this issue? Added a FAQ, README entry, or something?

**Comment by mondersky** [comment]
You need to run the command **Remove Sticker/Background** (ctrl + shift +p to open the command prompt) before uninstalling. If you already uninstalled the extension you can install it back and run the command. If you want to keep the extension and the css changes you can use this [extension ](https://marketplace.visualstudio.com/items?itemName=mondersky.installation-corrupt-remover) to hide the installation corrupted popup.

**Comment by tiagoarroz** [comment]
I have ran the **Remove Sticker/Background** command repeatedly and the message keeps appearing even after reloading the window and restarting VS Code.
