### ISSUE TITLE
Unsupported with Visual Studio Code?

### ISSUE THREAD

**Issue by HiDannyZ** [doki-theme/doki-theme-vscode#41]
Hey, just wanted to let you know that when using the theme, there's a unsupported tag if look at the picture. It says that the Visual Studio is corrupted and asks that I reinstall lmao.
![image](https://user-images.githubusercontent.com/22123497/105557296-d9670c80-5cd9-11eb-818f-5738da983610.png)
![image](https://user-images.githubusercontent.com/22123497/105557411-2fd44b00-5cda-11eb-8374-6910743c17d1.png)

**Comment by Unthrottled** [comment]
Unfortunately, this is a known issue. VSCode does not support CSS customization without corruption. [Please see this github comment for the reason](https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312)

However, there is a workaround to removing the warning, you can follow this thread here:
https://github.com/doki-theme/doki-theme-vscode/issues/26#issuecomment-676180921

Where you prompted with this the first time you installed stickers?

![image](https://user-images.githubusercontent.com/15972415/93272629-86a1a500-f77b-11ea-8f6b-50b0443f9949.png)

Is there anything else that I could have done to help you be aware of this issue? Added a FAQ, README entry, or something?

**Comment by HiDannyZ** [comment]
Thanks!
