### ISSUE TITLE
unsuporrted

### ISSUE THREAD

**Issue by blvckmindslol** [doki-theme/doki-theme-vscode#48]
how to fix ? 
![awwwwwwwwwwwwwwwwwwwwwwww](https://user-images.githubusercontent.com/79656732/109186905-5a7b5d00-77cc-11eb-9e4f-bcb7e801f980.PNG)

**Comment by Unthrottled** [comment]
Unfortunately, this is a known issue. VSCode does not support CSS customization without corruption. [Please see this github comment for the reason](https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312)

However, there is a workaround to removing the warning, you can follow this thread here:
https://github.com/doki-theme/doki-theme-vscode/issues/26#issuecomment-676180921
