### ISSUE TITLE
Partial selection disappears in DokiTheme

### ISSUE THREAD

**Issue by master117** [doki-theme/doki-theme-vscode#62]
**Describe the bug**
Partial selection / selection in selection disappears in DokiTheme

With Dark+

![image](https://user-images.githubusercontent.com/444009/115189261-80472300-a0e6-11eb-874e-94a98dc86b9d.png)

(_misc is selected, vsc does this double selection indication thing.)

With Rem

![image](https://user-images.githubusercontent.com/444009/115189395-af5d9480-a0e6-11eb-9835-12f0c5f0787e.png)

(_misc is selected, but you can't tell.)

Even worse with white items

![image](https://user-images.githubusercontent.com/444009/115189537-e633aa80-a0e6-11eb-87ba-8b57222759e7.png)

(highlightBg is selected)

Windows and latest VSC + Doki Theme. Same issue with other color themes than Rem.

**Comment by Unthrottled** [comment]
I'll assume that Dark+ highlights the current "chunk" (I dunno the technical term) the caret is an you can select characters within that "chunk". I think I've recently added some colors that I can use to fix this problem. I'll be able to look into this later this week. Thanks for bringing this to my attention!

**Comment by Unthrottled** [comment]
Hey I was in the neighborhood and fixed the issue here as well https://github.com/doki-theme/doki-theme-vscode/pull/63

When I get time later, I'll need to study [this](https://code.visualstudio.com/api/references/theme-color#editor-colors) and revisit the coloring.
