### ISSUE TITLE
The links of the Miku theme on the Welcome screen are Purple

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#73]
Posting here instead of doki-master-theme because I was unable to find a similar problem on the Jetbrains IDEs.

**Describe the bug**

On the Welcome screen, the links will be Purple on Miku's theme instead of a variation of Blue or Cyan.

![image](https://user-images.githubusercontent.com/11861253/119247483-da109200-bb57-11eb-946e-337ecc858132.png)

**To Reproduce**

1. Set the theme to Miku
2. Watch the Welcome screen

**Expected Behavior**

The color of the links are a variation of Blue or Cyan, like the previous version (12.1.0).

![image](https://user-images.githubusercontent.com/11861253/119247548-691daa00-bb58-11eb-8f43-0582a0aff3c0.png)

**Environment**

Version: 1.57.0-insider (user setup)
Commit: 29c61570a5b9a669f777bb28b5acd5c37d99edbe
Date: 2021-05-20T05:14:43.087Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
Doki-Theme: 12.2.0

**Screenshots**

See above.

**Comment by Unthrottled** [comment]
:thinking: Whoops, looks like they are supposed to be a shade of green. I'll fix that.

![image](https://user-images.githubusercontent.com/15972415/119264748-f50bf200-bba9-11eb-8a7d-46e701287754.png)

**Comment by Unthrottled** [comment]
Hey! So I know I didn't really fix _your_ issue, but this was an issue none the less.

If you want your links to be blue you can always [customize your workbench colors](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)

Here are the things you want to use to affect the link color if you want blue:

```json
    "textLink.foreground": "#0000ffAA",
    "textLink.activeForeground": "#0000ff"
```
Or some variation of that :)
