### ISSUE TITLE
Ubuntu Error

### ISSUE THREAD

**Issue by nitheum** [doki-theme/doki-theme-vscode#76]
I have the latest Doki theme extension in visual code.
I tried installing the echidna wallpaper but it failed.
It redirected me to the sticker installation help page.
In the page, it said to run "sudo chown -R $(whoami) /snap/code/65/usr/share/code/resources/app/out/vs/workbench"
I ran it at terminal and tried installing the echidna wallpaper. Still same error which is "Unable to install Echidna"

I also tried running visual code as sudo and ran the command, still didn't work.

This is the output of the aforementioned command:

chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/back-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/forward-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/letterpress-dark.svg': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/letterpress-hc.svg': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/letterpress.svg': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser/parts': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/continue-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/continue-without-debugging-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/pause-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/restart-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stepinto-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stepout-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stepover-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media/stop-tb.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser/media': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/node/telemetryApp.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/node/telemetryApp.nls.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug/node': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/debug': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser/media/language-icon.svg': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser/media/theme-icon.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser/media': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/extensions/browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/extensions': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal/node/TerminalHelper.scpt': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal/node/iTermHelper.scpt': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal/node': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/externalTerminal': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/notebook/common/services/notebookSimpleWorker.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/notebook/common/services': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/notebook/common': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/notebook': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/output/common/outputLinkComputer.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/output/common': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/output': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/fake.html': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/host.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/index.html': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/main.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre/service-worker.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser/pre': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre/electron-index.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre/index.html': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser/pre': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview/electron-browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/webview': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/colorTheme.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/commandPalette.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/debug.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/extensions.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/keymaps.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/languageExtensions.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/openFolder.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/openVSC.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/playground.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/scm.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/settings.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/settingsSync.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/shortcuts.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/splitview.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/tasks.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/terminal.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/forwardPorts.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/github.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/commandPalette.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/extensions.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/keymaps.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/languageExtensions.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/openFolder.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/settings.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/settingsSync.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/terminal.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/hc': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/commandPalette.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/debug.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/extensions.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/keymaps.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/languageExtensions.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/openFolder.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/openVSC.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/playground.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/scm.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/settings.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/settingsSync.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/shortcuts.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/splitview.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/tasks.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light/terminal.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/pullRequests.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/remoteTerminal.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/runProject.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media/tutorialVideo.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common/media': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted/common': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/gettingStarted': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser/media/commandpalette-dark.svg': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser/media/commandpalette.svg': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser/media': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay/browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome/overlay': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/welcome': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/workspace/browser/media/trusted-badge.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/workspace/browser/media/untrusted-status.png': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/workspace/browser/media': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/workspace/browser': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib/workspace': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/contrib': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.nls.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/node': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.nls.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker/httpsWebWorkerExtensionHostIframe.html': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/worker': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/search/node/searchApp.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/search/node/searchApp.nls.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/search/node': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/search': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.nls.js': Read-only file system
chown: changing ownership of '/snap/code/65/usr/share/code/resources/app/out/vs/workbench': Read-only file system

**Comment by Unthrottled** [comment]
Hey! So I've ran into this before, please see [this comment](https://github.com/doki-theme/doki-theme-vscode/issues/34#issuecomment-730028177)

I'll also probably put something in about snap being a jerk in the help screen. Let me know if you figure something out with `snap` or if you chose the `apt` route. Thanks!

**Comment by nitheum** [comment]
I uninstalled vs code which I installed with snap. Installed vs code with the apt route and it worked, thanks!

**Comment by Unthrottled** [comment]
Thanks for the follow up! I'll add something in the help guide for future `snap` install users.

**Comment by friendlymaninthisworld** [comment]
But still, it's kinda annoying that we have to reinstall Visual Studio Code to install the .deb one. I feel like we should still look into how to fix this.

**Comment by Unthrottled** [comment]
It's kinda annoying that I have to bastardize VSCode's CSS in the first place. That's the cards that we are dealt with at the moment. Until they give us first class support for CSS styling or adding/manipulating DOM elements, I gotta get to them CSS files to add anime girls. 

So those files got to be made writable somehow. Changing installations is my, "I don't feel like figuring this problem out , because it's easier to another installation method." You're more than welcome to tackle the problem though 😃 .

**Comment by friendlymaninthisworld** [comment]
Lol, thanks for being nice. Sadly, I don't really specialize in any of those languages.  But I'll try anyways just for fun. Love your stuff man.
