### ISSUE TITLE
The Doki Theme extension is completely disabled on an untrusted workspace

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#78]
Unsure if this is a VS Code bug or a Doki Theme bug, so I'm posting here first.

**Describe the bug**

On the Restricted Mode of VS Code, The Doki Theme extension is completely disabled. I feel that it should not be disabled as is just a theme and does not provides dangerous behavior.

**To Reproduce**

1. Set a theme from the extension in a trusted workspace
2. Switch to an untrusted workspace

**Expected Behavior**

The Doki Theme is available on unstrusted workspaces either in it's full capacity or with features limited (as defined by vscode).

**Environment**

Version: 1.57.0-insider (user setup)
Commit: 217f1a2f60a197807de78af362ecb832100fda96
Date: 2021-06-02T06:36:06.263Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
Doki Theme: 12.2.1

**Screenshots**

![image](https://user-images.githubusercontent.com/11861253/120954983-60170600-c71e-11eb-8578-1e6a91a72f93.png)

**Comment by justalemon** [comment]
From https://code.visualstudio.com/docs/editor/workspace-trust :

> Extensions that have either not explicitly indicated that they support running in Restricted Mode are shown in the Disabled in Restricted Mode section. An extension author can also indicate that they never want to be enabled in Restricted Mode if they determine that their extension could be misused by modifications (settings or files) in a workspace.

**Comment by Unthrottled** [comment]
🤔 Hmm, well I was able to use the theme when I trusted my open project. I'll look into this after I get done [with the next round of themes](https://github.com/doki-theme/doki-master-theme/milestone/5).

Thanks for the details!

**Comment by justalemon** [comment]
> when I trusted my open project

Exactly, the project/workspace needs to be trusted for The Doki Theme to work. As is just a Theme and nothing that can mess up the current workspace, it should probably be allowed even on untrusted workspaces.

**Comment by Unthrottled** [comment]
@justalemon I've got [v13.0.1](https://github.com/doki-theme/doki-theme-vscode/releases/tag/v13.0.1) published to the marketplace, so you no longer have to manually specify trust in your settings. Thanks for bringing this to my attention!
