### ISSUE TITLE
Wallpaper not available

### ISSUE THREAD

**Issue by Raesangur** [doki-theme/doki-theme-vscode#81]
On the latest version on the marketplace (12.2.2), the stickers option are available, but the background options don't show up when pressing Ctrl+Shift+P. I've reverted to version 12.2.1 and it works properly.

**Steps to reproduce**
1. Install latest version
2. Try to install a background
3. No background options

**Environment**
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363
Doki-Theme version: 12.2.2

Just wanted to let you know; I'm fine with running the previous version, it's probably a bug on my machine.

**Comment by Unthrottled** [comment]
That's curious, so on 12.2.2 you don't get these?

![image](https://user-images.githubusercontent.com/15972415/121508693-7daccf80-c9ab-11eb-9bbd-878c4c690b7a.png)

I'll have to check later on my windows machine.

**Comment by Raesangur** [comment]
Exactly, only the sticker options show up (as well as remove stickers and changelog).
I tried uninstalling and reinstalling it before installing the previous version.

**Comment by Unthrottled** [comment]
@Raesangur Could you try again? I've got [v13](https://github.com/doki-theme/doki-theme-vscode/releases/tag/v13.0.0) published.

**Comment by Raesangur** [comment]
I think I might have found the issue.
On the marketplace, it states that the current version is v13.0.0.
![image](https://user-images.githubusercontent.com/17782420/121904726-72350d80-ccf7-11eb-936a-518b23c73aaa.png)
But when I install it on Windows, it instead installs v7.1.0
![image](https://user-images.githubusercontent.com/17782420/121904804-837e1a00-ccf7-11eb-81c0-54e9aa090925.png)

**Comment by Unthrottled** [comment]
That's weird, have you tried updating VSCode?

This is the version I am running

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic
```

**Comment by Raesangur** [comment]
I've updated to 1.57.0 and it works now!
It properly installs v13.0.1 and wallpapers are available!

Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

Thank you!
