### ISSUE TITLE
Sticker and Wallpaper Not Working [macOS Big Sur 11.4 M1] [VSCode Insiders Latest]

### ISSUE THREAD

**Issue by KaiDevrim** [doki-theme/doki-theme-vscode#84]
I am on the latest version of VSCode Insiders
![image](https://user-images.githubusercontent.com/36937771/121992127-dd153180-cd55-11eb-9445-da5bdc96eb91.png)
These are the commands I use to install it.
![image](https://user-images.githubusercontent.com/36937771/121992181-fc13c380-cd55-11eb-939e-86c7d56429b2.png)
This is the colour theme I am using:
![image](https://user-images.githubusercontent.com/36937771/121992232-164da180-cd56-11eb-9a94-c4b04501ebf3.png)

And I am on the latest version of Doki Theme
![image](https://user-images.githubusercontent.com/36937771/121992257-21a0cd00-cd56-11eb-944c-6ed300a1c873.png)

**Comment by Unthrottled** [comment]
![image](https://user-images.githubusercontent.com/15972415/122038710-8599b480-cd9b-11eb-985f-3f449ca55fa5.png)

![No God, No God please no](https://media.giphy.com/media/12XMGIWtrHBl5e/giphy.gif)

**Comment by Unthrottled** [comment]
I'll have a fix out for this in a bit.

So much for being able to code offline :cry:
